### ISSUE TITLE
Red arrow next to article title is only clickable for article on left side of issue detail page

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#105]
On the [detail page for issue 1](https://startwords.cdh.princeton.edu/issues/1/), the red `>` character's hover and hyperlink behavior only works for "Data Beyond Vision" on the left side, but not for "Body as Data" on the right side.

I'm also wondering, should the article titles themselves also hyperlink to the article page, just like the excerpt text above does?

**Comment by thatbudakguy** [comment]
I think this can be closed, since the red arrows have been removed.
