### ISSUE TITLE
Contextual notes haven't been implemented for issue detail pages

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#106]
I don't think we've discussed this yet. The use case only occurred to me yesterday when thinking about writing my introduction to Issue 1: Transformations, and realizing that I would need to cite things. How should we handle citations / annotations / notes [on that page](https://startwords.cdh.princeton.edu/issues/1/)? I don't see why we shouldn't implement contextual notes for the issue introduction as well as the articles. But, @gissoo, will including endnotes at the bottom of the issue introduction text interfere with the white page / purple page boundary? I just tried one locally and here's how it shows up. (Markdown footnotes on the issue page currently render solely as endnotes, not as contextual notes *and* endnotes.)

<img width="589" alt="Screen Shot 2020-06-29 at 11 24 34 AM" src="https://user-images.githubusercontent.com/5580840/86024544-1e081f00-b9fb-11ea-862f-261f03ac5955.png">

**Comment by rlskoeser** [comment]
@gwijthoff I wondered about that! I think @thatbudakguy assumed contextual notes were for articles only (possibly based on the designs), but I don't think we ever discussed it or explicitly decided that. I kind of imagine once you have them you'll want to use them elsewhere...

**Comment by gwijthoff** [comment]
Does using contextual notes elsewhere detract from the specialness of how they're used in feature articles?

**Comment by rlskoeser** [comment]
@gissoo you never weighed in on this, very interested in your opinion when you get the chance.

**Comment by rlskoeser** [comment]
included in #224

**Comment by rlskoeser** [comment]
included in #224
