### ISSUE TITLE
Change content license from CC-BY-NC-SA to CC-BY

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#124]
After our conversation with university general counsel, we've decided to go with a less restrictive CC-BY license. This will involve:

- editing `config.toml` [@rlskoeser]
- redesigning the footer license image [@gissoo]

**Comment by gissoo** [comment]
@gwijthoff @rlskoeser @thatbudakguy 
I have revised the footer to CC-BY, [here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=331%3A204), please let me know your thoughts.

**Comment by rlskoeser** [comment]
Looks good to me!

**Comment by thatbudakguy** [comment]
fwiw @gwijthoff we usually reserve "enhancement" for completely new features, so even though this "enhances" the site by making its content more widely usable, it's not what we would normally think of as an enhancement

**Comment by gwijthoff** [comment]
![](https://media.giphy.com/media/l2Je2gRiEbNYvS6yI/giphy.gif)

**Comment by gissoo** [comment]
@gwijthoff @thatbudakguy is this ok? If ok @gwijthoff please close (unless it needs to wait for "editing config.toml [@rlskoeser]" which I just realize now is included in this issue)

**Comment by gwijthoff** [comment]
Since I rolled it all into this one issue, I think we still need @rlskoeser to edit `config.toml` with the license, and @thatbudakguy to implement your new design in the footer, before I close this one.

**Comment by rlskoeser** [comment]
@gissoo would you upload the new license image to replace the current one in static/img/logos/license.svg ?

Once that's done I will update the config (I didn't want to change it before we updated the image).

**Comment by gissoo** [comment]
@rlskoeser I just uploaded it!! Thanks!!

**Comment by rlskoeser** [comment]
Updated site config and tweaked the footer — someone want to review?

**Comment by gwijthoff** [comment]
@rlskoeser looks good! Thanks all.
