### ISSUE TITLE
As a reader, I want to read a short piece.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#13]
# dev notes
based on conversation with @rlskoeser, we want to treat this design-wise as almost identical, but implementation-wise we need to figure out how to differentiate them from long pieces - tags? a different content type? just do it by order of pieces in the issue?

**Comment by rlskoeser** [comment]
Closing based on @gwijthoff review of the PR and comments on the current implementation — doesn't make sense to test more right now since we don't have a final design yet.
