### ISSUE TITLE
turn on branch protection for main branch

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#133]
see [GitHub's docs on branch protection](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-protected-branches).

this would prevent commits that don't pass our lighthouse CI workflow from being merged into `main`. we'd want to do it after switching `master` to `main`, and perhaps after the release of the first issue.

i believe it would also effectively prevent committing directly to `main`, since you'd need to open a PR in order for tests to pass on the commit before merging it. personally, I'm OK with this since we don't expect super active development on this repository going forward.

i settled on this approach because i wanted to avoid running the github pages deploy workflow on broken or inaccessible code, but making separate github actions workflows depend directly on each other is difficult and not well-supported. there's [an example of a deploy that depends on another workflow](https://github.com/asarkar/build-time-tracker/blob/master/.github/workflows/publish.yml), but it uses a roundabout tactic of querying the commit status API to check if the other workflow actually passed.

**Comment by rlskoeser** [comment]
I just turned on branch protection for `main`

I configured it as follows:
- requires using pull requests
- requires at least one approval on the pr
- requires the **build site & run lighthouse** check to pass
- requires branches to be up to date before merging
- restrictions apply to administrators

If any of those settings end up being problematic, we can adjust.
