### ISSUE TITLE
revise designs to display tags on article page

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#140]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy I forgot to add this for review last week – I tried to apply the current all caps/small caps tag style to the article/snippet page and it doesn't visually fit, it adds a lot of visual inconsistency and imbalance. Last week RSK and I agreed that it would be nice if the tags on the issue page also look the same as they do [here, in the revised article/snippet version](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2295). (ignore the dark mode color - the color does not matter in this context)

**Comment by gwijthoff** [comment]
How would we feel about not capitalizing the first letter of the tag, i.e. `#experiments`? The lowercase letter might distinguish the tags field just a bit more from the authors above and the date below. A subtle change, just a thought!

**Comment by rlskoeser** [comment]
@gwijthoff I'm ok with that for single-word tags, but for multi-word tags using caps for starting words is important for accessibility / readability

**Comment by gissoo** [comment]
@gwijthoff, like @rlskoeser accessibility is my concern too and that is one of the main reasons I revised it this way as well, however for the sake of consistency I would prefer we always start with cap.

**Comment by rlskoeser** [comment]
I vote we close this issue.

We can switch from camel case to kebab case based on how we put the tags in the documents in Hugo, if we decide to go that route.

Here's a screen shot of how it looks:
![Screen Shot 2020-10-22 at 9 41 56 AM](https://user-images.githubusercontent.com/691231/96880487-350bca80-144b-11eb-95dd-49c80361fdc7.png)

When/if we add tag pages to the site I think we'd want the urls to be kebab case — but IDK that the url has to match the display.

My inclination is to keep the DBV tag the same as the one we're asking people to use on twitter, and twitter doesn't allow dashes in hashtags.

**Comment by gissoo** [comment]
@rlskoeser I don't think kebab case is a good idea now that you mention twitter doesn't allow it. Can we do this? #one but #notOne? Is this better than #One (which is what I am showing in the designs)?

**Comment by thatbudakguy** [comment]
> My inclination is to keep the DBV tag the same as the one we're asking people to use on twitter, and twitter doesn't allow dashes in hashtags.

Agree. I think #CamelCase is fine.

**Comment by gissoo** [comment]
@gwijthoff if you feel strongly, please do let us know.

**Comment by gwijthoff** [comment]
@gissoo CamelCase it is!
