### ISSUE TITLE
add tags to article detail page

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#141]

**Comment by rlskoeser** [comment]
@thatbudakguy I've already implemented the revised tags in #146/#112 — we can cherry pick if necessary, but I need to finish that branch and get it merged anyway!

**Comment by thatbudakguy** [comment]
is this done now?

**Comment by rlskoeser** [comment]
Yes! Tags are on article pages and tags styles have been revised on issue page — does it need to be reviewed?

**Comment by thatbudakguy** [comment]
looks good to me; only thing I'm seeing is that the tag `<li>`s probably need a right margin so they're not all smushed together. the designs don't show an article with two tags, so I'm just inferring this.

**Comment by rlskoeser** [comment]
wow, how did I miss that they were getting smushed? 🤦‍♀️

**Comment by rlskoeser** [comment]
@thatbudakguy can you fix this one? not sure when/if I will get to it
