### ISSUE TITLE
Homepage currently previews a snippet rather than second featured essay

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#156]
The “Print a Model” snippet is now featured on the homepage in place of RM’s essay, even though the YAML still has `order: 2` for the RM essay and `order: 7` for “Print a Model.” All essays and snippets have `date: 2020-10-01`, so that doesn't seem to be the issue.

**Comment by rlskoeser** [comment]
Not technically a bug because we haven't released yet

**Comment by rlskoeser** [comment]
Confirmed that it's now displaying correctly on the site.
