### ISSUE TITLE
Endnotes not showing consistently

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#163]
I haven't been able to reproduce this on my devices / browsers, but Camey reports that endnotes do appear at the bottom of the DBV essay, but *not* at the bottom of RM's essay on desktop running macOS Catalina. Her screenshot is below.

```
Camey  22 minutes ago
don't see them on safari

Camey  21 minutes ago
don't see on chrome

Camey  19 minutes ago
don't see on firefox

Camey  18 minutes ago
I do see them on my phone
```

![Screen Shot 2020-10-23 at 10 51 26 AM](https://user-images.githubusercontent.com/5580840/97020092-2262c580-151f-11eb-8aed-442423a4f3ed.png)

**Comment by rlskoeser** [comment]
Yes, I've been seeing this sporadically too — I have an idea about what's going on and some thoughts about fixing. Thanks for reporting so we can track it and test, though.

**Comment by rlskoeser** [comment]
Resolved by making the javascript `async` instead of `defer` (RMs essay loaded so fast in Chrome that the notes code was never initialized). Confirmed that the solution is working on the site now.
