### ISSUE TITLE
As a reader, I want to browse a list of all published issues.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#17]
# testing notes
[website link](https://startwords.cdh.princeton.edu/issues/)
[figma link](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1707)
this is the issue list page.

one note for design testing - as @rlskoeser noted, the design shows the red arrow appearing when each issue is hovered (but otherwise invisible). I have implemented it more in line with the red arrow elsewhere (e.g. on the homepage) - the arrow is always visible, but shifts subtly on hover. I can change it if that doesn't make sense here.

**Comment by rlskoeser** [comment]
Layout for a list of  issues is in startwords theme under layouts/issue/list.html and includes logic to loop over and link to all issues, and display the issue theme and content.

**Comment by gissoo** [comment]
@rlskoeser 
- I think the space between "Issue number" and "issue date" should be decreased to be 7px and the space between issue date and the theme should be 14px – sorry that Figma is not making this easier  

- Would it be possible that for all mobile the width of the content on this page would remain as is and not get wider? – I seriously think it will look so much better – but not sure if this is disastrous systemically.

**Comment by thatbudakguy** [comment]
I've adjusted the spacing between "issue number", "issue date", and the theme.

For the resizing - it's possible, but I'm not sure how to make it interact with our grid. I have defined the content container for this page (and others) to span from grid column 2 to column 9 on mobile, and from column 4 to column 7 on tablet, since that's what's depicted in the design. If the device is a different size from our breakpoint, the grid will be scaled to fit it, so the actual size of the content may change, but it will always take up the same amount/percentage of screen space. Both pictures below are inside our mobile breakpoint; one is ~375px wide (iPhone) and the other is ~700px wide. I don't think there are realistically many phones above 400px wide (the XS Max is 414px).

![Screen Shot 2020-06-01 at 3.05.11 PM.png](https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/6a7b068c-4852-4b28-90c4-9f575369f043)
![Screen Shot 2020-06-01 at 3.04.58 PM.png](https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/6169517e-6992-4545-931e-2fdc62e9c6e8)

We could switch to just using an absolute maximum width, so that the content doesn't resize except at breakpoints, but if we do that it seems like the grid isn't actually useful, since it only applies to devices that are the exact size of our breakpoint. On my end, I would change everything to not use the grid at all, because we would only care about the width values generated using it. Moreover, we would always need to size things according to the absolute smallest device size to avoid being cut off, so the content container would basically be scaled to 320px for every type of device all the way up to computer screens. That seems pretty restrictive to me.

Does this make sense?

**Comment by gissoo** [comment]
> I've adjusted the spacing between "issue number", "issue date", and the theme.
> 

- Thank you so much!! This looks perfect on all iOS browsers (FF, Chrome, Safari) – it still looks wrong on all desktop browsers (FF, Chrome, Safari) – is it because we said we wouldn't be customizing desktop? (If that's the case it's fine with me, it's not really bothering me) – 
<img width="1456" alt="Screen Shot 2020-06-01 at 3 51 57 PM" src="https://user-images.githubusercontent.com/44615389/83448369-d86a2d80-a41f-11ea-92aa-b2606b31327c.png">


> For the resizing - it's possible, but I'm not sure how to make it interact with our grid. I have defined the content container for this page (and others) to span from grid column 2 to column 9 on mobile, and from column 4 to column 7 on tablet, since that's what's depicted in the design. If the device is a different size from our breakpoint, the grid will be scaled to fit it, so the actual size of the content may change, but it will always take up the same amount/percentage of screen space. Both pictures below are inside our mobile breakpoint; one is ~375px wide (iPhone) and the other is ~700px wide. I don't think there are realistically many phones above 400px wide (the XS Max is 414px).
> 
> ![Screen Shot 2020-06-01 at 3.05.11 PM.png](https://camo.githubusercontent.com/c25982f4518b6e52cea5f4ef7e187f78152d109e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561613832633462346235383036626332626361623466612f36613762303638632d343835322d346232382d393063342d396635373533363966303433)
> ![Screen Shot 2020-06-01 at 3.04.58 PM.png](https://camo.githubusercontent.com/14afb67d677a033a41c9bdbdfc09ddc39737b8fe/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561613832633462346235383036626332626361623466612f36313639353137652d363939322d343534352d393331652d326664633632653963366538)
> 
> We could switch to just using an absolute maximum width, so that the content doesn't resize except at breakpoints, but if we do that it seems like the grid isn't actually useful, since it only applies to devices that are the exact size of our breakpoint. On my end, I would change everything to not use the grid at all, because we would only care about the width values generated using it. Moreover, we would always need to size things according to the absolute smallest device size to avoid being cut off, so the content container would basically be scaled to 320px for every type of device all the way up to computer screens. That seems pretty restrictive to me.
> 
> Does this make sense?

- Thank you so much for explaining, makes a lot of sense!! It sounds pretty disastrous to me, and I agree with you. Let's leave it, it's perfect as is :)

**Comment by thatbudakguy** [comment]
> is it because we said we wouldn't be customizing desktop? (If that's the case it's fine with me, it's not really bothering me)

correct. although your comment reminds me that we haven't really discussed a timeframe for working on desktop designs, and we probably should do that before we have a true 1.0 release...and if that's the case, we probably need to get you working on them soon so that we can implement them in the next iteration.

**Comment by gissoo** [comment]
@thatbudakguy Thanks for writing! Should I make issues for designing for desktop? (really it will be applying designs on desktop on my side)
