### ISSUE TITLE
As a reader, I want to preview all content for a single issue.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#19]
# testing notes
[site link](https://startwords.cdh.princeton.edu/issues/1/)
[figma link](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736)
this is the single issue page.

I wasn't sure exactly what margins to put on the clickable chevron/down arrow thing because of how the figma pages are split up...let me know if this look/interaction matches what you were thinking. you should be able to click it to zoom to the featured content section.

There are no links to short pieces yet, we will implement that with #13.

**Comment by rlskoeser** [comment]
Layout for individual issue is in startwords theme under layouts/issue/single.html and includes logic to loop over and link to all pages in the issue.

**Comment by gissoo** [comment]
@rlskoeser 

This is awesome!! 
A couple of points: 
- It would be so great if we could push down the arrow along with the purple section further down a bit, it would look so much better, the arrow would make more sense too

- The width of the content in the top portion of the page is supposed to be 294 on tablet which was agreed upon, it's now in the range of 438.8-591...for tablet. 

- Can we bring the arrow slightly to the middle for desktop? So it's not on the left as it is now? – If not, not a big deal for now.

**Comment by thatbudakguy** [comment]
- another note for myself - we decided that the arrow would have the same slight movement behavior when hovered as the red link arrows on the homepage, so that needs to be added

**Comment by thatbudakguy** [comment]
todo overhaul for section coloring:
- [ ] make grid a mixin/utility class
- [ ] remove margin from `main`
- [ ] make all children of `main` have gutter padding (not margin) by default
- [ ] apply grid utility class to sections
- [ ] apply inverted utility class to sections

**Comment by thatbudakguy** [comment]
@gissoo I tried something on this that I'd love feedback on - if you test on mobile or tablet, the first "page" (the white part) should always take up exactly one screen; when you tap the arrow it should scroll you to the second "page" (the purple part). if this makes sense and fits with your vision of the design, let me know! for desktop I think we will need to do something different, but I'm sure you're working on that already.

**Comment by gissoo** [comment]
@thatbudakguy Thank you! I just tested on iOS (all browsers) – the white part takes more than one screen (i.e. it's longer/requires scroll to see the arrow) so when you get to see the arrow you already see the top of the purple portion as well which makes the arrow useless. 

The way you have described it/might have intended for it to work, works perfectly on desktop mobile (narrowest desktop window) and all widths really on desktop – on all browsers – the white part takes the exactly one screen and the arrow is well within sight so when you click on it, it takes you to the purple part in a flawless manner/smooth transition. 

@rlskoeser @thatbudakguy 
(One side note I just noticed separate from this issue: if you click on the purple arrow and you scroll up back to the white part, and copy the URL, the URL still belongs to the purple portion :D – I understand why this is happening, however it might be kind of confusing for users – it can be solved if the user clicks on the <-- arrow on the browser to go back a page, however it's not the first thing the user thinks of because the white part is visually just a scroll away from the purple part, does this make sense?)

**Comment by thatbudakguy** [comment]
hmm...something strange is going on here. I tested on my phone and the two parts are the correct sizes, but you have to touch the arrow twice to get all the way to the purple part! gotta do some more work to figure out what's going on for mobile browsers. thanks for testing!

**Comment by thatbudakguy** [comment]
here's what I've found so far:

- the "smooth scroll" behavior isn't supported on Safari or mobile Safari, so we won't ever get the smooth animation on those browsers.
- in mobile Chrome, the "smooth scroll" works great - no problems.
- in mobile Firefox, having "smooth scroll" turned on creates the bug I discovered where the screen won't scroll all the way to the content unless you tap the arrow twice. If "smooth scroll" is turned off, the arrow works correctly - it just jumps you there instantly which is a little jarring.

for screens that are quite small (not many phones are below ~375px, but the iPhone SE is one of them) you will see the issue @gissoo found - the text pushes the purple arrow "below the fold", so you can't see it initially, and then the purple part is right there so the arrow is sort of pointless. for all other screens (iPhone 6/7/8, tablet, etc) this issue doesn't seem to occur.

**Comment by thatbudakguy** [comment]
if we used javascript for the scrolling effect, we should be able to achieve the same smooth motion across all browsers, and also avoid the issue of "linking" directly to the purple section as @gissoo noted. this will work on all mobile/tablet browsers since you can't really turn off js using them.

for computer users who have js turned off, clicking the arrow would do nothing, but maybe the desktop design can take that into account? I think the arrow itself still implies "there's more content down here", so maybe people would just scroll down anyway.

@rlskoeser @gwijthoff do you have thoughts?

**Comment by thatbudakguy** [comment]
one question I have is how long we expect the intro text for issues to be - a few sentences? a single paragraph? more?

if it's quite short, we might never run into the issue @gissoo found because there won't be enough text to push the arrow down the page. on the other hand, if it's longer, this approach of making the white/purple sections fill the page might not work.

**Comment by gwijthoff** [comment]
@thatbudakguy good question. I've thought of the intro text for issues to be a single paragraph. Let's say no longer than 300 words. Does that help clarify things?

**Comment by gissoo** [comment]
@thatbudakguy thank you for writing, this is very helpful!! So many constraints and shaky UX without JS it seems like ...:(

**Comment by thatbudakguy** [comment]
testing this further, if we want the white portion to fit on one screen it seems like there's really only space for about 80 words in the introductory paragraph, at most. @gwijthoff is that still too restrictive?

**Comment by gwijthoff** [comment]
@thatbudakguy white portion to fit on one screen for mobile, or mobile and desktop? Either way, I'd say yes, 80 words is too restrictive. I've been thinking about what it would be like to invite guest editors for future issues, and 80 words isn't much space to give them for encapsulating the issue theme.

**Comment by thatbudakguy** [comment]
more than 80 words would only cause problems on mobile, but we can't show more of the content depending on the screen size, since we have to render it in the HTML beforehand.

OK - I think we need to kick this back to @gissoo for how to proceed. How should we handle cases where the upper white portion has to be taller than one screen? What would happen to the purple arrow & the scrolling behavior?

**Comment by gissoo** [comment]
@thatbudakguy In such cases I can still imagine that you would scroll to reach the bottom of the white portion where the purple arrow is and then click on the purple arrow to see the purple portion. In other words, 
can we set a max height for the white portion? 
Can that max height differ based on the screen size break points? 
Can we set a max height for the white portion depending on the number of characters/words?

**Comment by thatbudakguy** [comment]
> can we set a max height for the white portion?

yep!
> Can that max height differ based on the screen size break points?

absolutely. I think we'll probably only need to set it on mobile, since tablet and desktop should have plenty of space.
> Can we set a max height for the white portion depending on the number of characters/words?

unfortunately I don't think this is possible. we can either do an absolute measurement, or a measurement based on the device's screen size - e.g. "150% of the screen's height".

**Comment by thatbudakguy** [comment]
ok, I've tried this again with some sample content that's closer to 300 words (much larger!). it now has a js-based smooth scrolling solution, so should work the same across all devices.

@gissoo let me know what you think about the spacing around the purple arrow; it could be increased if need be.

**Comment by gissoo** [comment]
@thatbudakguy Thank you for working on this. I think we just have to live with this (for long issue descriptions). So this is how I was imagining it to work: The white portion is basically a separate page from the purple portion but they have the same URL, does it make sense? :D This would mean that no matter how long the issue description is the scroll would be at the bottom of the page for the user by the time they reach the purple arrow, so there will be no way for them to see the purple portion unless they select the purple arrow. I understand if this is not possible and this looks fine as is for this issue. We can think more for later issues and revise if we want to.
