### ISSUE TITLE
revise issue list theme word wrapping

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#190]
For this issue: add logic so we don't wrap if the theme word is short (like scribes), but preserve existing wrapping/display for transformations / issue 1

Suggested approach: revise the `issue/summary.html` template to set a no-wrap class based on theme word length, and then adjust the css so it doesn't apply.  (Note: this is a provisional implementation and will likely be revisited for issue 3, so doesn't need to be totally extensible or configurable).

**Comment by kmcelwee** [comment]
Remaining Todos:
- [ ] Use the existing CSS Grid classes to center Credits section 
- [ ] Change footer color to grey
