### ISSUE TITLE
As a reader, I want to see all the authors who have contributed content to Startwords so I can see the range of contributors and find articles by authors.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#20]
# dev notes
this page is not designed, but might be similar to the masthead/project staff list (#21). we can try using the already defined text styles for now and see if it needs further design.

- [x] initial data structure & template
- [x] fix co-author display
- [x] implement styles
- [x] language chips

**Comment by rlskoeser** [comment]
Authors have been implemented as a [hugo taxonomy](https://gohugo.io/content-management/taxonomies/). 

We will probably want to add [custom metadata](https://gohugo.io/content-management/taxonomies/#add-custom-metadata-to-a-taxonomy-term) — maybe ORCIDs at a  minimum? We'll probably need to customize the author list and individual author layouts.

The author list is visible here:
https://startwords.cdh.princeton.edu/authors/

I think we could get by without this feature for the first issue turn off the author taxonomy, but I think we will want author info for citation metadata.

**Comment by thatbudakguy** [comment]
based on discussion today we are moving this out of MVP, since it implies designing both the author list page and author page.

**Comment by rlskoeser** [comment]
functionality is complete, final style revisions merged into develop
