### ISSUE TITLE
As an editor, I want to use interlude styles on any article so that I can highlight content using startwords-specific visuals.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#204]
essays in issue 1 and 2 both use interludes as article-specific styles; we should consolidate the common styles and incorporate into main theme styles, and remove it from the article-specific styles

**Comment by gwijthoff** [comment]
An important application of the interlude style I just saw in Lauren's article: she includes a screenshot of [this table](https://data-feminism.mitpress.mit.edu/pub/2wu7aft8/release/3#nobxi408tlj). It would be nice to use a markdown table instead, with the purple background of our interlude style.

Scroll down just a little to see how it currently looks in markdown on the Render site, without interlude styling: https://startwords-dev.onrender.com/issues/3/llm-limit-case/

**Comment by rlskoeser** [comment]
reviewed and merged into develop in pr #271
