### ISSUE TITLE
investigate and prototype hugo multilingual functionality

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/startwords#213]
https://gohugo.io/content-management/multilingual/
* When spanish material is populated, it’s used as the default on the front page of startwords. We’ll need to update that logic to select by language.
* I wasn’t able to get the language configs to work as expected in `/themes/startwords/config.toml`, only the root directory’s `config.toml`
* `.isTranslated`—the boolean variable Hugo sets to true when there are multiple languages configured—wasn’t set when testing the partial `i18nlist.html`.
* `about` is the only menu item in the config. We’ll need to add `issues`, since it is currently hardcoded. Otherwise, clicking on “Ediciónes” will jump to the english version. We will also need to reconfigure the home button.
* If we don’t translate all essays into spanish, we will need to update the issue summary script to include english essays. Otherwise only one essay will appear.
* A spanish user would only see one issue on `/es/issues`. Is that okay?
* We’ll need to decide how/if to change the view to show that a Spanish version is available. We'll need a yes/no on showing it on (1) the front page, (2) the issue page, and (3) the article itself. 

---

Hugo recommends this tool, I haven’t had much success in using it.
* [GitHub - nicksnyder/go-i18n: Translate your Go program into multiple languages.](https://github.com/nicksnyder/go-i18n)

```sh
brew install hugo
export PATH=$PATH:$(go env GOPATH)/bin
go install github.com/nicksnyder/go-i18n/v2/goi18n@latest
goi18n extract # extract all i18n codes used
merge active.en.toml translate.es.toml # populate translate.es.toml with the messages to be translated.
```

**Comment by rlskoeser** [comment]
converting this into an investigation/prototyping chore and opening issues for specific functionality based on design
