### ISSUE TITLE
As a reader, I want to download an article as plain text.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#23]
# dev notes
from @gwijthoff's note: https://github.com/Princeton-CDH/startwords/issues/5#issue-562716249:
> Article content in .txt files is currently generated using the {{ .Plain }} page variable, but there doesn't seem to be a way to customize that output format in Hugo, in order to introduce blank lines between paragraphs.

**Comment by rlskoeser** [comment]
Plain text is configured as an output format in the site config.toml

Plain text layout for a single article is in the startwords theme under layouts/article/single.txt

The html template for an article includes a link to the text version.

**Comment by rlskoeser** [comment]
Figured out how to tweak the plain text to put blank lines between paragraphs, which looks much more readable to me.

I think this is done and ready for review.

**Comment by gwijthoff** [comment]
Nice, simple fix. Looks great!
