### ISSUE TITLE
As a reader, I want to get the DOI of an article so I understand it's a scholarly publication and can cite it.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#24]
## testing notes
Check that the DOI for articles displays everywhere articles are listed, and particularly on the article page (ignore styles, they are not yet complete) and make sure they match the doi that is set in the article page metadata.

**Comment by rlskoeser** [comment]
Revised article html & text layouts to include DOI if set.

**Comment by gwijthoff** [comment]
Verified that DOI listed in article YAML appears where it should on article page and TXT version of article. The DOI URL currently isn't found, but I'm sure that's because the file is still listed as "draft" on Zenodo rather than "Published." So this one is good to go.
