### ISSUE TITLE
As a reader, I want to retrieve an article via a persistent URL.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#25]
# testing notes
this may already work 100% using Hugo's slug functionality, just need to verify that it does (and set some guidelines around slug usage).

**Comment by rlskoeser** [comment]
Pages under issue folders (which includes articles based on the way we're organizing files) are configured to use slugs for permalinks in the config.toml file. 

By default, an article url will be generated from a slug based on the title. If we ever need to change a title after publication, we can override the slug in the page metadata to keep the url from changing.

**Comment by rlskoeser** [comment]
I think this is ready for review/test also. At least, I can't think of anything else that needs to be done.

**Comment by thatbudakguy** [comment]
confirmed today:
- articles will use their defined `title` to form a slug if none is specified
- if an article is an `index.md` inside a named folder, the article will still refer to the `title` to generate a slug
- if a slug is specified, it will always override the `title` or folder name

so, we just need to write & enforce guidelines for setting a slug.
