### ISSUE TITLE
Create a mock up of the proposed author list page structure 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#251]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff please check out the three variations I have come up with[ here on Figma](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3233%3A12420)

- there are descriptions next to each regarding what makes each one different regarding the type styles and the order of the content – please let me know what you think

**Comment by rlskoeser** [comment]
@gissoo thanks for your work on designs for this new page!

I like v 1.2 better than 1.1, but I don't feel strongly about that.

The order you propose in version 2 doesn't work — the issue information is associated with the article, not the person, and one person could publish in more than one issue (although it hasn't happened yet). If you wanted to put the issue above the article title, that would be technically feasible — but I'm not sure whether that order is logical.

However, seeing this design and thinking about your feedback on the content order Grant and I came up with gave me an idea — if you think it would be useful to people, we could have a different page that lists all articles by issue. It could be sort of parallel to authors (could call it articles?), and would let people scan through all the content in one place in a way that isn't possible right now.

**Comment by gwijthoff** [comment]
@gissoo I have to admit that from a purely aesthetic standpoint I like your version 2 better, with issue above author name. All of the different text weights and colors look more balanced. However, as @rlskoeser points out above, from a functional standpoint it wouldn't work if an author publishes in more than one issue (which is bound to happen at some point).

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff thank you!! Your comments are so helpful!! I had ideas for the cases where one person has written for more than one issue, but I totally agree that placement is not helpful and logical at all ...I think what I should have really proposed was [this version here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3324%3A8951) – what do you think? I just really think it's better if it comes above the article title – it would be really helpful in grasping the site content overall (for consistency reasons)

![Screen Shot 2022-04-15 at 5.06.59 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/fff0152a-b2a0-4e00-b7de-c94c3c46f59c)


@rlskoeser I really don't think having a page that lists the articles by issue is necessary! Maybe I'm missing something but I can't see how that's different from an issue detail page other than the fact that you can scroll to see all on one page (which IMO is not a factor that would make it worth building that page)

**Comment by rlskoeser** [comment]
@gissoo that ordering works for me! If there are multiple articles by the same author from the same issue, do we repeat the issue?

Glad you don't think it's worth building a page with a list of all articles, one less thing to do :-)

**Comment by gwijthoff** [comment]
I agree with you both that there's no purpose of a separate page listing all articles per issue. And @gissoo, the new design looks great. Once you answer RSK's question above about multiple articles by the same author in the same issue, I think we're ready to close this issue.

And @rlskoeser, if you want me to take a first crack at implementing Gissoo's designs over in #249, I'd be happy to so long as it won't make more work for you to clean up my amateur CSS that it would to just do it yourself! I'm good either way.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff thanks!! @rlskoeser so you're saying if in the case that I had listed more than one article under issue 3, for instance, in the latest design? I don't think the issue info should be repeated, could it act as a way to "subgroup" the articles? So we display it once and all articles that belong to it would appear below it?

**Comment by rlskoeser** [comment]
@gissoo yes, that's what I wanted to know — it makes sense to me not to repeat the issue information (and is nice not to take up the space). Does the spacing need to change any so the content hierarchy is clear, or will it be obvious enough from context?

**Comment by gissoo** [comment]
@rlskoeser I was thinking to make the spacing a bit more generous – I'll ping you when I have done it – planning to work on the mobile version of this now, will hand them to you together.

**Comment by gwijthoff** [comment]
@rlskoeser that makes sense. And sure, I'm happy to reorder the content in the `authors/list.html` layout based on Gissoo's designs.

Not sure how Nick was thinking about efficiency, but switching to variable in the case of Source Sans lends a modest saving of space. Individual font weights for 200, 300, 400, 700, 900 was 20 files, 360 KB. The variable font is 2 files, 287 KB.

Seems like that doesn't belong in this PR though, so we can discuss elsewhere / later. Implementing variable fonts properly will mean calling the font weights in a slightly different way, maybe with the help of a tool like [Wakamai Fondue](https://pixelambacht.nl/2021/wakamai-fondue-command-line/) ("what can my font do?"). There are other benefits too. A discussion for another time!

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff I have finalized the designs for desktop and mobile based on our agreements, had to clean up the auto layout and spacing quite a lot: [here is a link to the desktop version](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3340%3A11081) – [the mobile version is here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3340%3A11357) – I have made annotations about the type sizes and the spacing (on mobile it's pretty similar to desktop, except what I have annotated) – please let me know if you need anything else for this issue.

**Comment by rlskoeser** [comment]
@gissoo that looks great to me. I can't think of anything else we need from you, looks like everything we need to implement the final designs.
