### ISSUE TITLE
Design for the Author list page label/link in the site navigation 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#252]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff if we are still thinking of placing the page title on the footer then what do you think of this rearrangement in the footer? [desktop](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3340%3A11081), [mobile](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=3340%3A11357)

Many won't really see this though – I think we talked about linking to it from the About page too (potentially)?

**Comment by rlskoeser** [comment]
@gissoo those look great to me! I agree, it would be good to add a mention and link on the about page as well as including it in the footer.

**Comment by gwijthoff** [comment]
Looks good, thanks @gissoo
