### ISSUE TITLE
body text is indented on Firefox between ~1074 and 1448 width

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#264]
Seems to happen only for this Issue 2 article, on both main and development sites: https://startwords.cdh.princeton.edu/issues/2/datas-destinations/

![Screen Shot 2022-05-20 at 3 23 32 PM](https://user-images.githubusercontent.com/5580840/169607841-2468f66f-8e72-43ec-a3f9-63be2b05afff.png)

**Comment by rlskoeser** [comment]
@gwijthoff thanks for the detail that only this article is affected – it's something related to the styles for the video! Not sure how to fix yet, but that's why it's specific to this one.
