### ISSUE TITLE
Horizontal scroll & multiple languages seen in contextual notes

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#270]
During the copyediting process, Camey noticed a long horizontal scroll in the contextual notes, and both English and Spanish text appearing one after the other. Her screenshot is below. She got this effect on Chrome and Safari.

![Screen Shot 2022-05-24 at 8 58 24 PM](https://user-images.githubusercontent.com/5580840/170320414-38121f0a-c12f-48a0-9dbe-72b0fa6b3004.png)

**Comment by gwijthoff** [comment]
Camey says she's on a Mac, but is also seeing the behavior on her phone. It's just a few notes, not all of them.

**Comment by rlskoeser** [comment]
@gwijthoff what branch is this happening on?

**Comment by gwijthoff** [comment]
@rlskoeser Editorial staging. I see it now too in Safari. And that was just a citation source in Spanish, so the Spanish edition footnotes aren't in there (phew!). I think the problem is that long URLs don't wrap like they do in Firefox:

https://startwords-dev-pr-263.onrender.com/issues/3/on-spanish-parrots/

**Comment by rlskoeser** [comment]
pushed a fix to the editorial staging branch
