### ISSUE TITLE
As a reader, I want to navigate around the site using the footer. 

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#28]
## testing notes
Implemented for mobile and tablet based on [figma footer component](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=331%3A204)

Please test on multiple pages to see both versions (dark and light) and different devices or screen sizes.

**Comment by rlskoeser** [comment]
There's a footer in the startwords theme under layouts/partials.

**Comment by rlskoeser** [comment]
@gissoo the white logos looked a little too stark, I have them set as off-white right now (I figured out a way to use the black logo as a mask so I could configure the colors in the CSS). Please let me know if you want the colors adjusted, it's easy to do in the CSS.

**Comment by gissoo** [comment]
@rlskoeser could you please try the "light grey" color so it will match the color of the light footer? To save you some time: it's #E9E9E9 – This way we won't have too many color variations

**Comment by rlskoeser** [comment]
@gissoo sure! Updated on the site now.

**Comment by gissoo** [comment]
@rlskoeser 
- Thank you! This looks great! 
- I'm sorry, looking at it on the site, I don't think the positioning I had designed for the logos in the footer work well, I have revised it in the components page on Figma, could you please move them so that the CDH logo would align with "About"? I think it will solve the problem.

**Comment by rlskoeser** [comment]
@gissoo thank you! I tried to match the designs but I couldn't get the centers to line up exactly the way they do in Figma even though I thought I had the spacing and positions pretty close. I like your solution, will make that adjustment.

**Comment by gissoo** [comment]
@rlskoeser Thank you. I also noticed the spacing between the logos and the license are closer than what I have in the designs. Is there a way to increase the spacing between them a bit?

**Comment by rlskoeser** [comment]
@gissoo sure - that might be because I was trying to get the about to line up with the startwords logo. What spacing do you want me to use?

**Comment by gissoo** [comment]
@rlskoeser the cdh logo is 15px away from Startwords logo, and the Startwords logo is 24px away from the license. (on all devices)

**Comment by gissoo** [comment]
@rlskoeser this looks so much better! Thank you! I think I'm done reviewing this!

**Comment by gwijthoff** [comment]
The purple footer is a straight line for me on mobile, rather than the angle shape on tablet and laptop. Is that intentional? 

I think that's the only question I have!!

[IMG_5456.PNG](https://images.zenhubusercontent.com/5e6fa2284847cbacb75fdd35/5bf2e905-c1e6-4f7c-aae7-03a8d615bd16)

**Comment by gissoo** [comment]
@gwijthoff Omg! Thanks for catching this! I just checked and it seems like it's only happening on all sized devices on Safari. It's not intentional, something is happening on Safari.

**Comment by rlskoeser** [comment]
@gwijthoff thanks for catching that! I think I've corrected it now, please confirm.

**Comment by gwijthoff** [comment]
@rlskoeser all fixed — thanks!
