### ISSUE TITLE
missing space between introduction author names

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#288]
For some reason, I can't replicate this bug when serving locally. But on the Render site for the develop branch, at the base of the introduction, there's no space between the first author name and the word "and" [in English](https://startwords-dev.onrender.com/issues/3/) or "y" [in Spanish](https://startwords-dev.onrender.com/es/issues/3/).

**Comment by rlskoeser** [comment]
confirmed resolved on dev render site by changes in #305
