### ISSUE TITLE
translator should only be named beneath Spanish introduction

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#289]
Currently, at the base of the Issue 3 introduction in English, the translator's name is mentioned. I'm not wedded to this, but it might make sense only to include the translator's name beneath the Spanish version that he translated.

**Comment by rlskoeser** [comment]
@gwijthoff just looked at the template, it's supposed to be displaying as "Spanish translation by ..." but we're missing the english translation for Español in our translation files.  Current implementation would list all translated languages and translators on all pages (once we add the languages to our translation files). 

Let me know what you prefer:
- always display all translators and languages
- only display translator for the current version (with no language indicator, I guess?)

**Comment by gwijthoff** [comment]
Ah, gotcha. In that case, it seems option 1 is better: always display all translators and languages.

**Comment by gwijthoff** [comment]
resolved by #292
