### ISSUE TITLE
display issue for two-digit footnotes

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#301]
numbers for two-digit footnotes are getting stacked because the width is set explicitly for single digit size

tested in both firefox and chrome

![Screen Shot 2022-08-01 at 5 03 38 PM](https://user-images.githubusercontent.com/691231/182246485-a9ef9715-1175-4cef-997b-b399f35ee09b.png)

**Comment by gwijthoff** [comment]
Resolved by #302
