### ISSUE TITLE
single issue page doesn't include publication date

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#309]
I was checking the date for a Startwords piece recently and was surprised that there were no dates on the single issue page (e.g., [issue 3](https://startwords.cdh.princeton.edu/issues/3/). You have to click in to the article to see a date.   We do include dates on the [issue list page](https://startwords.cdh.princeton.edu/issues/).

There is also no date on the issue as displayed on the homepage — I think @gwijthoff needs to weigh in on whether we want it there or not (my vote is yes).

I propose we add the date to the single issue page using a format and layout similar to what we have on the issue list and article details.

**Comment by gwijthoff** [comment]
Addressed in #328
