### ISSUE TITLE
Restructure the visualization on the fanqie pronunciation system to highlight sounds and the cognitive experience 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#315]
Note:

- The point of this visualization: Nick explains that in Old Chinese when they wanted to say a word they would look for examples, for instance they wouldn’t have said “flight”, they would have said “fish+light-ish” i.e "fish and light but remove the ish."
- Proposals: let's add sound to this because the point of this concept is the sound and can be communicated more effectively through sound, and let's restructure it so we can highlight the combination and subtraction factor more effectively. 
- This is how Nick and I revised it at our meeting.  
![Screenshot 2023-05-23 at 6.51.23 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/2ed0bffb-f5c1-48ee-8109-e99decc361ac)

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @GDRom [what do you think about these two proposals](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4536%3A10549&t=zk5NiAoIqREV5X5k-1)? (the only difference is in the colors).  

The proposal reflects my conversation with Nick, where we discussed reorganizing some of the information and the hierarchy to make the character/word combination process more prominent and make the rest of the info more contextual and connection with the rest of the info.

**Comment by gissoo** [comment]
I was chatting with Nick earlier, unsure how to visually show the subtraction process we had talked about in Chinese: for instance 'they would have said “fish+light-ish” i.e "fish and light but remove the ish." ' – since it's not possible to visually separate the pieces of a Chinese character

**Comment by gissoo** [comment]
Also, I think having two audio files, one on the word "east" itself and one that says out loud the process of combining the characters to get to "east", what do you think @thatbudakguy @GDRom?

**Comment by rlskoeser** [comment]
I don't have a strong preference between the colors; I like the purple if we think we will have other interludes in the piece (which I imagine we may). Does it make sense to hold off on deciding color until we know about the other visuals?

I find the LTR orientation of parts easier to follow than in Nick's original diagram; do we still need the labels for the different pieces of information conveyed?  

The detached floating ear looks a little too realistic, it bothers me for some reason. 

I'm not sure we can get the default audio player to look like that, but probably feasible with an existing library (which may be preferable for accessibility anyway).

**Comment by thatbudakguy** [comment]
I like the way this is laid out; it seems simpler and easy to process. I also like the idea of having separate audio for the word, and for its "parts".

Maybe it would even be simpler to just have one audio file per word? So there would be one clickable audio button for 德, one for 紅, one for 東 (and one for fish, light, and fight). The "+" and "=" don't make any sound.

About the highlighting, I see that on the english words, the highlighting is kind of subtle (but noticeable). The reason I put the highlighting on the transcription in my initial example was so that you could also do highlighting on the Chinese words (since you can't do it . What if we just underlined the part of the transcription that was used? So:

/<ins>t</ins>ək/ + /ɣ<ins>uŋ</ins>/
/<ins>f</ins>ɪʃ/ + /l<ins>ʌɪt</ins>/

it's subtle, but at least it would let you highlight something on the chinese side.

**Comment by rlskoeser** [comment]
@thatbudakguy is there a clever way we could highlight part of the Chinese character, maybe with a special background? Or is that not worth the effort / likely to be unreliable?

**Comment by thatbudakguy** [comment]
Maybe I can explain why that doesn't work...

The character 東 signifies the concept of "east". As an ideogram, it doesn't have any inherent sound — it's a picture or idea that signifies something. If I was in japan, I'd pronounce it like "tō" (it's the first part of "Tokyo"). If I was in china, I'd pronounce it like "dong".

There are no components of 東 that have any relationship to either of those two pronunciations. If you were to remove parts of the character, it would lose its meaning — like a drawing with random shapes erased from it.

**Comment by rlskoeser** [comment]
@thatbudakguy wow, thank you for explaining! Yes, that's helpful.

**Comment by gissoo** [comment]
thank you both for writing. @rlskoeser I also kept asking Nick about separating the characters on slack :D it's unfortunate that we can't somehow visualize it ...

We can definitely decide on colors later. I'll revise the ear a bit to make it more pleasant to the eyes. I think it's more fun to have it there. 

@thatbudakguy based on your feedback I revised the viz. [I did what you showed above](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4536%3A10549&t=PnkagP3NIgX1k2Xj-1) and also [did a version I like better with transparency instead](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4553%3A10430&t=PnkagP3NIgX1k2Xj-1). Let me know what you think.

**Comment by thatbudakguy** [comment]
I like both of them! I think the transparency version is more pleasing, but I guess the one possible issue is accessibility of color contrast between the transparent letters and the background. Although maybe we'll just have a single accessible description or caption for the whole graphic, so that might mitigate it somewhat. And there are other cues in the image that help you figure out what's going on.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy do you like [any of these revisions on the ear](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4566%3A10530&mode=design&t=5lpTCc5YNgGbLFbb-1)?

**Comment by rlskoeser** [comment]
@gissoo I like this direction! (making it larger and moving it to the margin). I like the third one best (line drawing)

**Comment by thatbudakguy** [comment]
I agree with rsk, and I like the line drawing one a lot!

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy Amazing! Thank you. [I've included both of the line drawings and have created the mobile versions in both colors as well](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4633%3A12403&mode=design&t=ukqU8SSpN13AYV09-1). 

I'll go ahead and close this issue.
