### ISSUE TITLE
Provide translations for #7 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#317]
@thatbudakguy Notes from our conversation:

The point here is that in his notes, Lu Deming, would specify the parts of the book his instructions about a particular word would apply, for instance “x is the pronunciation, follow this/it applies to the entire chapter 1" 
Nick would find a good example so we could work on this
Gissoo: it would be nice to provide a line of text and then break it apart and annotate the parts
Nick: it would be good to provide a translation

**Comment by rlskoeser** [comment]
@gissoo @thatbudakguy is this task still relevant / needed / incomplete?

**Comment by gissoo** [comment]
@rlskoeser this is already resolved through Nick's current example for figure 7. I had forgotten that I had written this issue!!!
