### ISSUE TITLE
On mobile, IIIF figures don't allow the user to scroll

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#323]
When scrolling down Nick & Gian's SW4 article on mobile, the user gets trapped when they reach a IIIF figure. The IIIF image takes up the entirety of the screen, and when attempting to scroll lower down in the article, the user is only able to move the IIIF image around.

**Comment by rlskoeser** [comment]
@gwijthoff good catch, thanks for flagging; is the height generally good and we should just set a mobile-specific style to make sure we limit it so we don't make a scroll trap?

**Comment by gwijthoff** [comment]
@rlskoeser the height of the image itself is good, i.e. leaves enough space to touch outside the image. But the whitespace surrounding that image (part of the IIIF viewer? I don't know) seems to be what takes up the entirety of the mobile screen.

**Comment by rlskoeser** [comment]
fix merged into develop in PR #330
