### ISSUE TITLE
Links in interludes have insufficient contrast

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#325]
**Describe the bug**
Linked text in interludes (purple sections) uses the link color meant for white backgrounds, so it's not very distinguishable on a dark (purple) background.

**Expected behavior**
Maybe use a slightly darker (or lighter?) version of the light text color?

**Screenshots**
<img width="211" alt="Screenshot 2023-09-03 at 14 00 40" src="https://github.com/Princeton-CDH/startwords/assets/4924494/e46d1c68-5c6f-4735-bb92-62e9de002cce">

**Device information**
 - Device: MacBook Pro
 - OS and version: macOS 13.5.1
 - Browser and version: Arc 1.6.0 (Chromium 116.0)
 - Site version: preview?

**Comment by gwijthoff** [comment]
Whoops, I didn't see that you already reported this issue! I already addressed it with [this commit](https://github.com/Princeton-CDH/startwords/pull/326/commits/ffec5b102a5e378f9a0b47cf4430fcf8d25a62b2) in #326. I'll close this issue, but please let me know if there's a better solution.
