### ISSUE TITLE
Add typeface and type styles for CJK characters in SW4

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#331]
@rlskoeser Some context based on our final design decisions: 
- we are keeping the IBM Plex Serif for latin characters and Noto Serif for non-latin characters. [Here you can see what it would look like for Nick's and Gian's article](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4634%3A10388&mode=design&t=Xs2BsT0kOmVh0oIU-1) and [here you can see what it would look like for Aliz's piece](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4634%3A10491&mode=design&t=Xs2BsT0kOmVh0oIU-1)
    
Note: to make them fit better I have reduced the Noto Serif by 2px, i.e. it is always 2px smaller than IBM Plex Serif. On desktop it's 18px and on mobile it's 16px.

I think[ this is the source where I got the font ](https://developers.googleblog.com/2017/04/noto-serif-cjk-is-here.html)

**Comment by gwijthoff** [comment]
Resolved in #333
