### ISSUE TITLE
Implement the visualization for figure 3 to communicate the parallelism instances 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#345]
@rlskoeser here is the finalized static version on [desktop](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4848%3A2354&mode=design&t=rtmzpZvDIRBbs1Kh-1) and [mobile](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4853%3A2453&mode=design&t=rtmzpZvDIRBbs1Kh-1) – I have included the revised interactive version on the same page as well just in case.

Notes: 
- There are auto layout container through which you can inspect spacing but let me know if you have any questions. 
- The faded text are still the same dark grey that exist on the site (#404040) but with 30% opacity 
- The sources on desktop are 16px and 14px on mobile (are a mix of Noto Sans CJK and Source Sans Pro). 
- Do you need assets for the underlines here as well?

**Comment by rlskoeser** [comment]
Thanks @gissoo. Grant and I wondered about whether we needed a sans serif CJK font or could just let the browsers use a fallback font. Can we get by with a single weight of Noto Sans CJK? Do we just need regular / 400?

In terms of assets: I think these may all be feasible with pure css; I'd rather not use an image if we don't need one.

**Comment by gissoo** [comment]
@rlskoeser I think the 400/regular weight is the only one I used in the Noto Sans CJK! That would be amazing! Yes, please let's just use that weight in the Sans.

**Comment by rlskoeser** [comment]
@thatbudakguy assigning this to you since I think you agreed to handle the things that are left to revise.  I'll look for it when you're ready for review & merging.

**Comment by rlskoeser** [comment]
completed in #364
