### ISSUE TITLE
Implement the visualization for figure 7 that communicates the Jingdian Shiwen annotation 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#346]
@rlskoeser Here is the finalized version on [desktop](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4855%3A2736&mode=design&t=rtmzpZvDIRBbs1Kh-1) and on [mobile](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4855%3A2895&mode=design&t=rtmzpZvDIRBbs1Kh-1). 

Question for you: Since I have customized the height/length of the underlines based on dimensions of content would you want me to upload all of the underlines as unique assets? Or just upload the longest versions? 
like the below ...[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXFhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e8892873fb0dde91b53ddf588db266f287bdf5a/Screenshot%202023-09-14%20at%201.51.19%20AM.png)

Note: 
- on desktop and mobile there are auto layout structures through which you can inspect the spacing and margins. The way it's structured might be a bit strange on desktop as there are nestings but it's the way that made the most sense to me. Please let me know if you have any questions. There is a unified 24px horizontal spacing on desktop between each word/character. 
- on mobile because of the way I have structured the auto layout I had to cheat and put the off white backgrounds (#fefefe) behind the text, so here is the specs for top and bottom margins of the content within the off white boxes: 8px.  

## development work
- [x] restructure html
- [x] styles for new layout
- [x] annotation border image styles
- [x] Noto Sans CJK

**Comment by rlskoeser** [comment]
@gissoo thank you for creating the issue and documenting all of this.  Please export the smallest version of the underline images that can be used to repeat/tile and get the desired pattern; i.e., one dot with appropriate spacing, one squiggle, etc.

**Comment by rlskoeser** [comment]
@gissoo CSS border supports dots! `border-style: dotted;` see https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

It's possible to generate a wavy border using a radial gradient; I don't know how hard to translate your designs to that, but here's one tool that will help you generate the CSS: https://css-generators.com/wavy-shapes/ - but it does look quite like your wave pattern. 

I don't think the squiggle or circles can be done without a tiling image, though, so I'll still need assets for those.

**Comment by gissoo** [comment]
- @rlskoeser [here are the underline patterns prepped for you](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?type=design&node-id=4949%3A6269&mode=design&t=VlNbyIa1Kyv5ZnhQ-1) – I have taken the smallest bit of each that can be used to recreate the patterns and have put them in an autolayout container, so you can actually inspect the horizontal spacing for the circles, and you can also try to recreate the shape in the autolayout by copying and pasting the shape inside the container if you want to test it in Figma anytime. 

- Note: I used the dash line property on Figma for the dashed underline, I can't break that down, but I have included it here so you can inspect the properties of the dash line by clicking on it. It has a width of 6px and dash length of 4px with gaps of 4px. 

- Also, I tried to recreate the squiggle using the link you shared. Below is the closest I could get it to be. the width of my drawing is 4px, but below it looks very thin, and the thicker I make it the pieces start looking broken and detached. If you can use the design it might look better than the version below.
<img width="865" alt="Screenshot 2023-09-15 at 1 16 56 PM" src="https://github.com/Princeton-CDH/startwords/assets/44615389/64007023-7b74-4b5e-ad91-5e860696b0d7">
here is the css code:  
.box {
  --mask:
    radial-gradient(39.24px at 50% calc(100% + 25.65px),#0000 calc(99% - 4px),#000 calc(101% - 4px) 99%,#0000 101%) calc(50% - 54px) calc(50% - 15.5px + .5px)/108px 31px repeat-x,
    radial-gradient(39.24px at 50% -25.65px,#0000 calc(99% - 4px),#000 calc(101% - 4px) 99%,#0000 101%) 50% calc(50% + 15.5px)/108px 31px repeat-x;
  -webkit-mask: var(--mask);
          mask: var(--mask);
}

**Comment by rlskoeser** [comment]
@gissoo I have done some work to implement with the assets you gave me but I need some revisions for them to work.
- the tile-able version of the image needs to include the whitespace for the space between portions of the image; I tweaked the circle and dot but not sure I got the spacing right
- the tile-able version of the image should be continuous; I think it's ok if it overlaps; your green squiggle has a gap between tiles currently
- it looks like I need different assets for the mobile; at least for patterns that are different when rotated, but maybe for all of them since it seems they are different sizes. (maybe @thatbudakguy can come up with a different approach that doesn't require this? it seems complicated)

**Comment by gissoo** [comment]
@rlskoeser so glad he resolved this! the separate svgs for mobile was definitely complicating it.

**Comment by rlskoeser** [comment]
designs implemented in #351 by @rlskoeser and @thatbudakguy 

noto sans cjk still TODO

**Comment by rlskoeser** [comment]
noto sans tc implemented and reviewed on #360
