### ISSUE TITLE
incorporate audio for SW4 feature 1 figure 6

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#347]
- [x] incorporate audio files 
- [x] implement layout and audio player design
- [x] adjust spacing for the figure; decrease extra space on tablet, only include on mobile when needed for the visual

**Comment by gwijthoff** [comment]
@rlskoeser do you have a preferred way for me to send you Gian's audio files? Or a location on the site for me to push them?

**Comment by rlskoeser** [comment]
@gwijthoff I was copied on the email, so I have access. I'm not sure yet where they should go or what format I need, I may need to convert.

**Comment by rlskoeser** [comment]
completed in #361
