### ISSUE TITLE
Standardize formatting of captions across figures, tables, deepzoom, and other embeds

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#366]
Currently, captions for our figures, tables, deepzoom images, and more include manually entered text for the numbering and naming of those captions. Some abbreviate figure "Fig.", others spell it out. We should follow the Chicago Manual of Style so that all captions across these media types read:

`**Figure 1.** An image of something.`

Figure should be spelled out, a period should be placed after the number, and "figure," number, and period should be bold.

I could go in and individually change the figure, deepzoom, and table shortcodes to add a variable for figure number along with formatting for that text, but I figured you'd have a more programmatic way for doing things, @rlskoeser. Can we define a CSS class somewhere central and then pull it into those individual shortcodes?

Another question: is there an easy way to automate the numbering of those captions, so that when an image gets moved from the top of an article's text to the bottom, the figure number automatically updates in relation to the order of the other figures? If that's too complicated, we could just make an additional variable in the Hugo shortcodes for figure number.

**Comment by rlskoeser** [comment]
completed in #366 (whatever was missed in previous pass by @gwijthoff )
