### ISSUE TITLE
As a content editor, I want to quickly create issues and articles using templates.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#37]
# Testing notes

- [x] Given the [instructions in the startwords readme](https://github.com/Princeton-CDH/startwords/tree/develop/themes/startwords#generate-new-issues-and-articles), can you easily make an issue and a few articles? Could anything be more clear? 
- [x] Deploy the site, is the content displaying as expected?

# dev notes
this corresponds to using `hugo new` with a configured issue or article archetype to create a preset bundle of content. see [the hugo docs](https://gohugo.io/content-management/archetypes/#directory-based-archetypes) for an example of directory-based archetypes.

**Comment by gwijthoff** [comment]
@kmcelwee @rlskoeser I tried running the [instructions in the startwords readme](https://github.com/Princeton-CDH/startwords/tree/develop/themes/startwords#generate-new-issues-and-articles), but the command `hugo new --kind issue issues/3` seems to create a file with no extension in the `/issues` directory that contains the following:

```
---
title: "3"
date: 2022-02-02T12:25:14-05:00
draft: true
---
```

The behavior I expected was for that command to create a directory `issues/3`.

I've created an [editorial-staging](https://github.com/Princeton-CDH/startwords/tree/editorial-staging) branch for editorial housekeeping on Issue 2, adding Contributor Style Guide and Editorial Guidelines pages to the site, and to stub out Issue 3. I'll just add an issue 3 manually on that branch since I want to get it over to Gissoo by next week, but wanted to flag the problem with our theme's custom `hugo new` command.

**Comment by gwijthoff** [comment]
@rlskoeser I ran it on that new editorial-staging branch I created, which was based on main

**Comment by rlskoeser** [comment]
@gwijthoff thanks for clarifying — seems reasonable for your editorial staging to be branched from main and merged back in, but issue 3 work needs to be based on develop

**Comment by gwijthoff** [comment]
@rlskoeser that makes sense. I'll do all of the issue 3 work on develop. To clarify, you don't think the problem with the `hugo new` command is due to my running it on a branch based on main, do you? In other words, is `hugo new` only built to work on develop?

**Comment by rlskoeser** [comment]
@gwijthoff right — the new archetypes aren't available on `main` yet, so it couldn't work there; eventually it will be available in main once we merge in issue 3 and all the related updates

**Comment by rlskoeser** [comment]
@gwijthoff you're right to flag this, an absolute file path would cause a problem.

The hugo documentation on [file variables](https://gohugo.io/variables/files/) says that `File.Dir` returns a relative path; I just I tested this locally myself, and I got a relative path (although it did not have a leading `/`, which I think we need). I'm not sure why you and I got different results, though. 

Did you try this before you upgraded Hugo? Did you run it from the main startwords directory?

**Comment by gwijthoff** [comment]
@rlskoeser I just reran, and the path I got this time was relative: `["issues/4/test-article/images/social-media-preview.jpg"]`. Must have been an issue with the older version of Hugo I was using.

So, I think that means this issue can be closed.

**Comment by rlskoeser** [comment]
whew, glad the upgrade solved it. We do need the leading slash, though, so still needs a minor edit. 

@gwijthoff were the instructions otherwise clear, as well as the default values in the pages created from the archetypes?

**Comment by gwijthoff** [comment]
@rlskoeser Now that you ask, it did occur to me that "images" isn't the most intuitive description for what that YAML category does (specifies the social media preview image). When I first saw "images", I assumed it specified the directory for all of the article's images. Can we change it to be "social_preview" or something like that, or is "images" predetermined / required by Hugo?

Just made some minor changes to the wording in the instructions: https://github.com/Princeton-CDH/startwords/commit/30906f4f71cb89ef79659a8ccb6855eb1ffe0627

**Comment by rlskoeser** [comment]
@gwijthoff the `images` parameter name is used by the built-in Hugo templates for opengraph and twitter preview - see https://gohugo.io/templates/internal/#the-internal-templates 

Would it help to add a comment to the template, to provide context?

**Comment by gwijthoff** [comment]
@rlskoeser ah, I see. I think a comment in the template might be helpful, as long as you don't think it clutters things. Like:

```
images: ["/issues/4/test-article/images/social-media-preview.jpg"] # specifies social media preview image
```

**Comment by rlskoeser** [comment]
added the suggested comment to the template, I think with the other wording updates this one is finished now
