### ISSUE TITLE
Caption for Figure 7 needs better positioning

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#371]
The caption for Figure 7 currently appears in a cell at the bottom of the table, but we agreed along with Gissoo and Nick that it would make more sense for the caption to appear at the top of / above the table, so readers understand how to read it upon seeing it for the first time. 

I tried several ways of re-positioning the caption but can't think of a way to do it semantically, i.e. without just plopping a disconnected `<figcaption>` above the table or interlude.

**Comment by rlskoeser** [comment]
Nick took care of this.
