### ISSUE TITLE
figure numbers and references for SW4 deepmap

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#376]
Removing/suppressing the first two images means the figure numbers in the rest of the text are off - both the labels in the figures and the references in the text (at least, I think they are - you know the text better than I do).

**Comment by rlskoeser** [comment]
I looked into auto-numbering; shortcodes have an `.Ordinal` property, but I don't think it's enough to let us auto-number the figures (it seems to be order in the doc of _all_ shortcodes, and now way to differentiate). We could ask on the hugo forums whether this is possible for improving this in the future. (Although you'd still have the problem of having to adjust references in the text...)

**Comment by gwijthoff** [comment]
I manually re-ordered the figure numbers in [this commit](https://github.com/Princeton-CDH/startwords/commit/3e48b9fcd49bf8184cb35d3f0640cfff986ed755). We'll revisit if we're able to re-add figs. 1 & 2.
