### ISSUE TITLE
Design the Single Issue page for mobile + tablet

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#41]
must contain:
- all metadata that belongs to an issue
- article excerpts 
- list of short pieces (links)
- links to articles 
- nav

**Comment by gissoo** [comment]
@gwijthoff I have revised the Single Issue page for mobile + tablet, they are here: 
(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1736)

Please take a look and let me know what you think. 
Note: I did not include any header for the links to short pieces on this page. Please let me know what you think about it and if you have an appropriate header in mind. (Related articles?) I wasn't sure what the header may be or if needs to exist. I imagine a header needs to exist here to give a little more context on why the links exist on the page at all.

**Comment by gwijthoff** [comment]
Hi @gissoo. The tricky thing about short pieces is that they won’t always be connected to one of the two articles. They might be about different topics altogether. Right now, you have the short pieces are listed beneath each article. That makes sense for issue 1, given that short pieces will be part of “Data Beyond Vision” [and article 2 will have no short pieces]. But I’m not sure how or if you’d like to indicate an approach for future issues, in which short pieces not connected to either article should be more centered on the page.

**Comment by gissoo** [comment]
@gwijthoff  Thank you for writing! I revised the short pieces, so that now there is none showing under article 2. 
@rlskoeser @thatbudakguy Grant and I discussed this and he said he would defer to us about this. I strongly suggest we place a header above the short piece links, for instance "related articles" ...or something to provide some context on why the links exist on this page at all (which will actually prompt them to select and view the links more than if there is no header). 
Note: the design you see attached to this issue shows the case where the short pieces belong to one article (placed directly under one article's data)

**Comment by rlskoeser** [comment]
@gissoo it seems hard to figure out how to label them when we're not labeling the feature articles.

I agree with Grant that we can't assume the short pieces will be associated with a feature and that it would be better if the design doesn't require that. 

What do you think about giving them a label specific to the issue, so the editor can describe or categorize them in some way? e.g. issue 1 could be something like  "more transformations" or "how tos and experiments" .

**Comment by gissoo** [comment]
@rlskoeser This is a great idea! Yes, sorry this is also what I had in mind. It came up as Grant and I were discussing, forgot to mention it above.

**Comment by thatbudakguy** [comment]
@rlskoeser do you think the naming/category of the short pieces would be something that gets stored in front matter, or just part of the text of the issue page?

**Comment by rlskoeser** [comment]
@thatbudakguy I think it would have to be a param in the issue metadata
