### ISSUE TITLE
Design the Issue List page for mobile + tablet

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#42]
must contain:
- issue number 
- issue date
- issue theme
- link to view the issue

**Comment by gissoo** [comment]
@gwijthoff 
Here are the designs for the issue list page for mobile and tablet:
(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A1707)

please let me know what you think.

**Comment by gwijthoff** [comment]
LOVE the big, line-broken text of TRANS-FORMA-TIONS!

Is the "Home" breadcrumb link needed if the S logo at the top left also navigates to home?

**Comment by gissoo** [comment]
@gwijthoff I think it's more systematic and consistent if the breadcrumb appears here, even though it may be redundant. (here, I would say it's more about the breadcrumb concept and building that up for the user)

**Comment by gwijthoff** [comment]
@gissoo makes sense!
