### ISSUE TITLE
As a contributor, I want to embed deep zoom images in pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#45]
# testing notes
note that this issue is written from the perspective of a contributor, so it isn't testing the way that deep zoom images look - just the _ability_ to embed them if you are writing an article. we will test the look of the deep zoom viewer as part of #12 since it's part of the design of an article/long piece.

you'll probably notice that the viewer is very wide (it stretches across the screen by default) but may not be very tall. once we apply the design to article pages, the margins will be set, so it will be a more normal size - ignore this for now.

to test this:
- make sure that you have an updated copy of master and check it out locally:
```sh
$ git pull origin master
$ git checkout master
```
- create a new article in any issue by copying one of the existing articles into a new markdown file. change the title (and maybe replace the body content with lorem ipsum or other placeholder text).
- in the new article, use the new shortcode for embedding a IIIF image:
```html
{{< deepzoom tile="..." height="...">}}
```
- for the value to replace the `...` in `tile=`, you can try any of these image URLs from PUL (feel free to try a few different ones by changing the value and reloading hugo).
  - a sheet of polka music `https://iiif.princeton.edu/loris/iiif/2/figgy_prod%2F42%2F1c%2F36%2F421c363889334d8cba9113f6dbbcaf52%2Fintermediate_file.jp2/info.json`
  - an ethiopic manuscript `https://iiif.princeton.edu/loris/iiif/2/figgy_prod%2Ff3%2F17%2F28%2Ff31728358d414cdd91a42d5780915f06%2Fintermediate_file.jp2/info.json`
  - a nevada mining map `https://iiif.princeton.edu/loris/iiif/2/figgy_prod%2Fda%2F96%2F89%2Fda968969c4bb4b7682dd95b28b77be2b%2Fintermediate_file.jp2/info.json`
- for value to replace the `...` in `height=`, try values like `10em` or `200px`. try varying the value and reloading hugo to see the height of the preview window change.
- have a look at the article page for your new article to see how the viewer looks.

if anything seems out of place or broken about the viewer, leave a comment below. if it works like you expect, feel free to close the issue!

**Comment by gwijthoff** [comment]
Was puzzled by receiving the following text in the embedded image viewer:

```Unable to open [object Object]: HTTP 0 attempting to load TileSource```

Until I realized that my EFF Privacy Badger plugin was blocking all cookies from iiif.princeton.edu -- not sure if that matters from our perspective. Once I turned the plugin off, everything worked perfectly.
