### ISSUE TITLE
Design a footer for the site for mobile and tablet 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#47]
must contain:
- About
- CDH Logo
- Creative Commons BY-NC-SA 4.0 license

**Comment by gissoo** [comment]
@gwijthoff 
I have created this version of the footer according to our conversations. It is in the "Containers" canvas. (For mobile and tablet for darker and lighter screens = a total of 4 footers)
(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=63%3A0)

Please let me know what you think. I tried the icons for the license instead of the text however there are 4 icons which are not necessarily comprehensible on their own, so I decided to keep just the text you had given to me in the comments.

**Comment by gwijthoff** [comment]
Hi @gissoo, some comments:

- what is the text: “We call them contextual notes, instead of footnotes!” Does that stand in for the text in the article that is connected to the contextual note at the end of it? Or will that specific sentence literally be included at the top of contextual notes?
- can we replace "CC BY-NC-SA 4.0 license" with the Creative Commons icons you include below the footer screen? The icons can hyperlink to the license itself: https://creativecommons.org/licenses/by-nc-sa/4.0/
- on the issue list page, the day isn’t needed (April 10, 2020), only month and year (April 2020)
- maybe swap the position of the “S” and the CDH logo, so that the Startwords S is symmetrically placed on the top-left corner of the page and also the bottom-right corner of the page

**Comment by gissoo** [comment]
@gwijthoff Thanks for writing.

1. Let's discuss this on an issue I'll create just for the footnotes, and not on here.

2. So if we replace the text with icons, we will need to include all the 4 icons, is that what you want? 

3. Thanks, can you comment this on the issue that is specific for the issue list please? I am looking at this github issue just to find out what I should do about the footer, sorry.

4. Let's also discuss this on the homepage issue #39, thank you!!

**Comment by gissoo** [comment]
@gwijthoff I have revised the designs to reflect your comments (available through the link above):
2. I have replaced the text with the 4 icons in all footers.
4. I tried this after we discussed, but I don't recommend it, because it gives the CDH logo more importance. 
I like the symmetry that it creates, however it won't be noticeable since on most pages the user will need to scroll down to see the footer (Unless the footer will always be sticky on all pages) @thatbudakguy @rlskoeser Will it? I don't think it's necessary for it to always be sticky.

**Comment by rlskoeser** [comment]
@gissoo it seems like your design has the footer not sticky, which seems fine to me (I could imagine it might be distracting when reading text content). I think it should be the same everywhere, though (not sticky on some pages).

Is the purple footer on purple background distinct enough?

**Comment by gissoo** [comment]
@rlskoeser I think on the single issue page it makes sense for it to be sticky. (because of the nature of this page)
I don't think it needs to be sticky everywhere. 

Thanks for pointing that out! I have revised the color!

**Comment by thatbudakguy** [comment]
imo if it is sticky in one place it should be sticky everywhere. either way is fine, but making it inconsistent is error-prone and also unpredictable.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy If we are strongly against making it sticky in only one place, then I would vote to not make it sticky at all, it won't make sense for shorter pages (especially on other devices).

**Comment by thatbudakguy** [comment]
fwiw also, the way i talk about footers:
"sticky" = it sticks to the bottom of the page if the content is shorter than the page (the [sticky footer pattern](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers)), but might not always appear on the screen if the content is long. it scrolls with the other content.
"fixed" = it appears at the bottom of the screen always, even if the user scrolls, and doesn't move. corresponds to [`position: fixed;`](https://developer.mozilla.org/en-US/docs/Web/CSS/position).

I assume we're actually talking about fixed here, but wanted to make sure.

**Comment by gissoo** [comment]
@thatbudakguy thanks for clarifying! Very useful! (meant to ask earlier and then I assumed it's self explanatory enough!! :|)  Yes I meant having a fixed footer for shorter pages won't make sense and is awkward and unnecessary. 

What do you mean when you say "...but might not _always_ appear on the screen if the content is long.."?

**Comment by thatbudakguy** [comment]
if you imagine a long article (which will probably be pretty common), when the user loads the page, they'll likely see:
- the header
- the first few paragraphs of the article

the footer will likely be several screen lengths further down the page, because it has to be after all of the content, so they'll need to scroll to see it.

sorry, i could've worded that better!

**Comment by gissoo** [comment]
@thatbudakguy Thanks this makes sense. I thought you were talking about scenarios other than the "length of the content". Wanted to make sure.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser So then if we do keep all the footers fixed, that grey footer on the "single issue" page should be deleted, correct? (I still do imagine the user will select the purple arrow and the page will scroll to the purple portion)

**Comment by rlskoeser** [comment]
@gissoo I don't think I had registered the grey footer on the single issue page! I think it should be deleted, and the user only sees the dark purple footer when they scroll down far enough. (I think it would be pretty difficult to make the footer change from gray to purple on the same page anyway, so I'm glad we're not attempting that).

**Comment by gissoo** [comment]
@rlskoeser Great! Will do! (Yes, I took it off that day when we were looking at it and then I was instructed to put it back ...so was getting a bit confused)

@rlskoeser @thatbudakguy Once you let me know about the license info and if it's changing I can revise this issue and then close it.

**Comment by rlskoeser** [comment]
@gissoo could we use this style license image instead? I agree that having four distinct images is problematic. I think this one may be more recognizable (although I'm underwhelmed by the image quality...):
![CC-BY-NC-SA](https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png)

There's also a compact version:
![CC-BY-NC-SA](https://licensebuttons.net/l/by-nc-sa/4.0/80x15.png)

I don't think this design issue should be held up by a possible change to the choice of license. How much does it impact your design if we decide to change it?

**Comment by rlskoeser** [comment]
Aha. Here's a better source for the images; they do have SVG versions. https://creativecommons.org/about/downloads

**Comment by gissoo** [comment]
@rlskoeser I had seen this page ...but I really don't want to use these images. I can add the text to the icons myself (and make them all into one SVG). The background of this image won't look very logical on a purple footer ...

Any change won't impact its position much, however we should remember to assign me an issue/chore again later to keep it updated in the design.

**Comment by thatbudakguy** [comment]
i like those icons because they're pretty universally recognized as corresponding to the CC licenses, but agree about the image quality, and that it might not look super great with our theme. @gissoo if you can cook up something better using the svgs that they provide, i'm down with that (if it doesn't take too much time).

**Comment by gwijthoff** [comment]
I'm kind of partial to the individual circle icons, i.e.

![](https://mirrors.creativecommons.org/presskit/icons/cc.svg) ![](https://mirrors.creativecommons.org/presskit/icons/by.svg)

The look cleaner to me than the buttons, i.e.

![](https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by-nc.svg)

But maybe that's just me. I'll defer to you on this, @gissoo

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff Ok I'll revise this myself taking into considering what you are all saying – because I really don't want to use exactly what they are visually offering – will work on it tomorrow.

**Comment by gwijthoff** [comment]
@gissoo We could potentially just include the CC icon alone, and have it hyperlink to the *specific* CC license we're using without using the other icons (BY-NC-SA, etc)

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy Based on all of your comments, I have these three variations of the footer (license info), please take a look and let me know what you think. 

(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=303%3A30)

**Comment by thatbudakguy** [comment]
I like v2, since it's the most concise and immediately recognizable description of the license. It isn't immediately clear from v1 which license is represented (though you could figure it out by reading each icon) and v3 doesn't describe the license at all.

**Comment by gwijthoff** [comment]
I agree with @thatbudakguy, v2 all the way! Thanks for updating these @gissoo. Worth mentioning here that @rlskoeser will be talking with university council about which CC license we should be using, and we may just end up going with CC-BY. Not sure if that changes your design calculus at all, but I thought I'd mention it before I close the issue.

**Comment by rlskoeser** [comment]
I like v2 also.

**Comment by gissoo** [comment]
@gwijthoff @thatbudakguy @rlskoeser Thank you for responding!! Great, will use v2 now. 
In the case of changing pieces of the license I can revise the rectangle and add or subtract elements from it and adjust the size of the rectangle.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff I have revised the footer. 
Please take a look at the updated footers here: 
(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=63%3A0)

And if you are ok with it, close the issue, if not, let's discuss.

**Comment by gwijthoff** [comment]
Looks good to go! 🦶
