### ISSUE TITLE
Design 404 error page 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#50]

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff please let me know what you think about the [404 pages here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1104%3A3516)

I had other ideas but it's a bit difficult to make them work here. I'm still thinking. I appreciate your feedback!! And any text you think of for this page.

**Comment by gwijthoff** [comment]
@gissoo v1 is so fun! I'm not sure about the placement of "Not Found" above the big 4. Maybe you only need "not found" or "error" but not both? Not sure: I've never thought too much about 404 pages. But I love the design of the 404 digits with their hints of the inlaid `>` characters.

**Comment by rlskoeser** [comment]
@gissoo I like the ideas in v1 and v2 too! I didn't see the `>` until Grant pointed it out — I think maybe it's more recognizable when the page is zoomed out, and not as apparent when you're zoomed into the page at normal size (or maybe I was just tired and looked too quickly! Now that it's been pointed out to me it seems so obvious).

I don't like the `0` in v1 as well — maybe too boxy? I think I like the square one in your drafts better (not sure why, it's still boxy! maybe something about the angles?)

The shapes in v2 are interesting to me but the numbers aren't quite legible to me (the 4 looks more like a tilted A).

Are the colors distinct enough from the logo? The purple seems ok but the red/pink bothers me a little (too close but not the same somehow, maybe?) Although when I look at the drafts and compare the other color combinations I really like the faded color choice you've used in v1 and v2. 

I agree with Grant, we probably don't need both "not found" and "error".  What do you think about angling the "not found" text to align it with the big `4` somehow? Either vertical along the right side or angled along the top left?

I'm interested in what @gwijthoff thinks in terms of tone and ideas for language for the 404 page. It seems like it would be fun to do something humorous or clever. The one idea that I've come up with so far is:
> Hmm, that one must be in our stopword list...

@gwijthoff happy to share 404 and 500 error pages from our other projects if it will give you any inspiration! I think they're all pretty good. I particularly like the language for Derrida's Margins — 500 page text is "a crack in the program" and the 404 text is "no trace".

**Comment by gwijthoff** [comment]
Stop all the words! I love that idea @rlskoeser! Let’s definitely use the stopwords phrase.

**Comment by gissoo** [comment]
@gwijthoff @rlskoeser having read your comments I continued going off of v1 and created more variations of this version, [here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1104%3A3516)

@rlskoeser For some reason I prefer the narrow "0" more because it looks more like a 0 to me than the round one, the round one looks more like an "O" to me. I have tried both here so you can see. I don't feel strongly though.

Please let me know what you think! I revised the language, the placement of text/the body language, and the "not found" label, that was a great suggestion, RSK, thank you!

@gwijthoff I thought of using either "not found" or "error" – I remember that during PPA RSK had noted how "404 error" is not necessarily inclusive, and having "not found" is very helpful. But I don't want to remove "404 error" because that's what I'm relying on here for visual design – unless I can come up with something else for visual design that doesn't use the "404".

**Comment by gwijthoff** [comment]
@gissoo ooo the outlined number forms in v4 are wonderful — the graphic language is much more clear, indicating that the numbers are built from our angle brackets. It is less colorful, however.

Also, understood re: using "not found" and "error." The way you've positioned them, far enough apart, works well.

**Comment by rlskoeser** [comment]
I like the new idea in v4 too! Could it work to make the outsides of the 4 using solid color blocks, maybe with the light purple? The lines you have made me think of negative space — like the 4 is between 4 pieces of paper laid out together, 3 in a grid and one at an angle.   (I don't know if that loses too much of your idea of using the angle brackets)

I like the angled "not found" text. Can it be bigger on tablet and desktop? (Or were you thinking it would be part of the image? That is easier for placement but harder to resize!)

Could the "stopword list" text be somewhere else on tablet/desktop? I like it better when the text is wrapped, but it seems too far down the page when it's under the 4.

You're right about the round 0! It's interesting how it looks different there than in the other draft. I think I would like it better if there were notches taken off some of the corners like the 4 has (but not sure if it is worth your time working on that!).

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff Thank you for writing!! Since you have both liked the new idea/the version with the outlines, please read below. 

I might have lost my sanity after reading @rlskoeser 's comment :D – [here are some more ideas](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1104%3A3516) and varieties next to "exploring the new idea" and "exploring based on RSK's comment" – This is happening because your feedback is great and is encouraging me to test and come up with more varieties. But if we want to move forward, let's pick one and go with it for now :D @thatbudakguy your feedback would be great!!

**Comment by thatbudakguy** [comment]
holy cow, these are so cool looking. nice work @gissoo!!

overall i like the the original idea a bit more than the outline but don't have a strong preference. the narrower boxy 0 looks good to me also. of the new versions, i like the ones against the dark grey background best, especially the white-on-grey.

**Comment by gwijthoff** [comment]
I think I agree with @thatbudakguy that I'm liking the original idea better. Maybe because it reminds me of a popsicle I used to love from the ice cream truck, but that's just as informed a design opinion than any, right?

@gissoo is there an option where we can do "narrow zero" but with text *up* so that "Hmm, that one must be in our stopword list…" is the first thing the user sees at the top of the page?

**Comment by rlskoeser** [comment]
Wow. For whatever it's worth, I love the new idea explorations and "exploring based on RSK's comment".

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy Thanks all for writing! Let me know if you have any thoughts or preferences regarding my comment below: 
Coming back to this after some time, I prefer that we use either V4b2 or a V5 because these are more aligned with the direction of our visual design in Startwords – @gwijthoff re: your question about moving up the text: I think we can move up the text but keep it on the same x-axis – visually it won't work for the text to be totally on top of the 404 shape or on its left.

**Comment by rlskoeser** [comment]
Looking at these again, I like V4b2 a lot. It seems like it is visually stronger than the others, and I think I understand what you mean by it fitting better with the rest of the visual designs.

Of the V5s I think like V5d best. But I like V4b2 better.

**Comment by gissoo** [comment]
@rlskoeser Thank you for writing. Can we go with V4b2? Shall I close this issue?

**Comment by rlskoeser** [comment]
@gissoo yes, let's go with that one! Will you update the designs in figma to make the final design clear before closing this issue?

**Comment by gissoo** [comment]
@rlskoeser Great, I just did [here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1104%3A3516)

@thatbudakguy @gwijthoff if you have any concerns let me know on Slack – Grant, I moved up the text a bit too.
