### ISSUE TITLE
Revise Article Contextual Notes

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#51]
I have revised the design of the contextual note,
one version for desktop, and another for tablet and mobile: [Here it is](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766) – Please let me know what you think

**Comment by gwijthoff** [comment]
Hi @gissoo: what is this text? “We call them contextual notes, instead of footnotes!” Does that stand in for the text in the article that is connected to the contextual note at the end of it? Or will that specific sentence literally be included at the top of contextual notes?

**Comment by rlskoeser** [comment]
I hadn't noticed the overlapping text (from the referring context?) and number until @gwijthoff pointed them out this morning. I would prefer not to show the overlapping text, and if the number matters I think it should be more prominent.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff I have revised the design of the contextual note,
one version for desktop, and another for tablet and mobile: [Here it is](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766) – Please let me know what you think

**Comment by gwijthoff** [comment]
Both look great!

**Comment by thatbudakguy** [comment]
two questions:
- what does the large background text represent? (it says "David Staley"). if it's intended to be the author mentioned in a citation, what if there are no (or multiple) authors?
- do notes still fill the screen on mobile? if not, for common mobile phones sizes (i.e. iPhone 6/7/8) which are slightly wider than 320px, there will be a thin but visible area around all sides of the note. this seems different from before.

I like the drop shadow around the note; I think on desktop especially it will help it stand out from the other text.

**Comment by gissoo** [comment]
@thatbudakguy The large background text represents the text with the superscript (at least the first two words with the superscript - to have a strong echo of what is being viewed – doesn't need to be complicated (I'm just using David Staley as a sample here to represent it as a text with superscript, a lot of times the text with superscript may be an entire sentence)

- They would be full-width on mobile – I think it makes sense for it to be full-width on all mobile devices (not tablet and desktop) – but I'm not sure what that entails when it comes to its visual design

**Comment by thatbudakguy** [comment]
oh gotcha, totally makes sense. thanks for explaining on both.

if we want to keep it full-width on all mobile devices I think we'd need to decide a width that represents the largest mobile device. the way we generally do breakpoints is that anything larger than X "is" device X - so anything larger than 320px width "is" mobile, and anything larger than 768px "is" tablet. if we want the notes to be full-width on all mobile devices but _not_ tablet, we would need to pick some width less than 768px at which point they stop getting wider and stay fixed-width. if we did something close to 768px, they would appear to have a very small border around them on, say, iPad (which is exactly 768px wide).

the largest mobile devices I have on my browser emulator are the iPhone XS Max and Galaxy Note 9, which both have a width of 414px. what if we said something like 450px or 500px as the maximum width of a contextual note? that seems like it would comfortably cover most mobile devices, but leave a reasonably large area around it on tablet.

**Comment by rlskoeser** [comment]
@thatbudakguy thanks for the specifics on mobile: I'm currently using one of the existing breakpoints but I did wonder if that was the right solution. I like your suggestion. @gissoo does it sound ok to you?

I'm not sure how to implement the "text with the superscript" — there's nothing in the markup that indicates what text "belongs" with the note, there's just a footnote reference. I don't know how we could infer how much text to use, and even if we could I don't know how we would implement this. @thatbudakguy can you think of a way to do implement this?

**Comment by rlskoeser** [comment]
@gissoo what color should links in footnotes be? Your mockups don't include any, but our footnotes often will.

**Comment by thatbudakguy** [comment]
You're right - I can't think of a way. The footnotes that we generate are tied only to the small superscript number itself, not any part of the text.

**Comment by gissoo** [comment]
> oh gotcha, totally makes sense. thanks for explaining on both.
> 
> if we want to keep it full-width on all mobile devices I think we'd need to decide a width that represents the largest mobile device. the way we generally do breakpoints is that anything larger than X "is" device X - so anything larger than 320px width "is" mobile, and anything larger than 768px "is" tablet. if we want the notes to be full-width on all mobile devices but _not_ tablet, we would need to pick some width less than 768px at which point they stop getting wider and stay fixed-width. if we did something close to 768px, they would appear to have a very small border around them on, say, iPad (which is exactly 768px wide).
>   @thatbudakguy It would be great if it can go back to 320 for tablet. 
> the largest mobile devices I have on my browser emulator are the iPhone XS Max and Galaxy Note 9, which both have a width of 414px. what if we said something like 450px or 500px as the maximum width of a contextual note? that seems like it would comfortably cover most mobile devices, but leave a reasonably large area around it on tablet.

Sure, @thatbudakguy I'm a little concerned with how the text will look in the container – can we look into it together? I think it does make sense for the container to be full-width for all mobile, but just want to make sure the text and all the content inside the container look appropriate.

**Comment by gissoo** [comment]
> @gissoo what color should links in footnotes be? Your mockups don't include any, but our footnotes often will.

@rlskoeser do you mean links within the note inside the container? (I think the same red should be fine)

**Comment by thatbudakguy** [comment]
@gissoo we can definitely have it just go back to 320 for tablet/desktop, yep.

**Comment by rlskoeser** [comment]
@gissoo yes, that's what I meant - links within the content of the note. I'd temporarily set them as white because the purple made them unreadable. I can switch to red.

**Comment by gissoo** [comment]
@rlskoeser thank you!

**Comment by rlskoeser** [comment]
@gissoo not sure how readable the red is on the purple, but you can check it out on the site.

**Comment by gissoo** [comment]
@rlskoeser I'm sorry I'm so confused where can I view this page on the site with the contextual note?

**Comment by rlskoeser** [comment]
@gissoo I added some more test notes to the DBV test/draft article, you can see how they look  here https://startwords.cdh.princeton.edu/issues/1/data-beyond-vision/ (sorry I didn't include a link)

**Comment by gissoo** [comment]
@rlskoeser I just saw what Grant has shared in General ....Ahh ...I see it thank you! – was probably moving fast on that page and didn't see the "1" superscript. Sorry I wasn't clear, I meant the red underline only, not red as also the color of the text – but I think even a red underline would not be visible – how about the lilac color? E0CEFF this?

**Comment by rlskoeser** [comment]
Sorry for my confusion/misunderstanding! I think it would be best if you update the designs in Figma to include a link example with the styling you'd like to see.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy I have revised the design of this now to include link example, [here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766).

Please let me know what you think and if more revisions are necessary.

**Comment by rlskoeser** [comment]
Link style looks fine to me. Do we have hover/active styles for links generally? (I don't know where that would be in Figma if we have them.) Do we need any of these specified here, or do all states look the same? 

Not really related, just thinking about link styles: any thought of custom select styles for users navigating by keyboard?

**Comment by gissoo** [comment]
@rlskoeser We don't have hover styles for links, and I don't think they are necessary – however you're making me think about this: I think it's better if I put all link/active styles in one place on figma? I haven't done that! – I think for this issue specifically what you see represents all the states

- Yes!! Thank you for thinking of this! I have thoughts! – Should I make an issue for it?

**Comment by rlskoeser** [comment]
@gissoo it would be nice to have one place in Figma for all link styles (at least the standard ones, I don't know if the contextual note links belong there?) Is it kind of a "component" ?  

An issue for select styles makes sense to me! Would be nice to start including that when we think about design, otherwise it's too easy to forget. (IDK if this should be MVP, but probably also not hard to implement...)

**Comment by gissoo** [comment]
- @rlskoeser Great! No it's not a "component" but I think it is a "Style" and should be included since it is "clickable" and a behavior is expected
- Great! Will create an issue for it

**Comment by rlskoeser** [comment]
@gissoo can we drop the shadow text from the context of the note reference? We don't have a way to do that.  

I can't find it now, somewhere did you comment about flipping the direction of the arrow icon pointing to/from the reference? I can see it working either way.

Other than that, I think these designs are good.

**Comment by gissoo** [comment]
- @rlskoeser that's sad!! It visually adds so much to the container! I understand and suspected about whether it can be done – I can also do some research on it if helpful for the future. 

- re flipping the arrow – what I meant was that it would be upwards – woah I didn't articulate well what I meant – I was imagining a much more complicated animation – now that I think about it, it would make more sense if it's just an "x". What do you think?

**Comment by rlskoeser** [comment]
@gissoo sorry I didn't get back to this.

Sorry I was unclear about the width of the clickable region - fixed width is fine. I think you've provided values elsewhere for that.

Somehow I don't like the 'x' icon as well as the arrow, but it does seem more logical for the functionality. I'm fine with that if you are.

FYI, I've had some ideas about how to implement the shadow text in future — if you wanted to make an enhancement to track the idea, I'd be ok with that. However, both of my ideas are fairly complicated, so I think I'd want to see some user testing on the feedback before implementing.

**Comment by gissoo** [comment]
> @gissoo sorry I didn't get back to this.
> 

Thanks for writing!! 

> Sorry I was unclear about the width of the clickable region - fixed width is fine. I think you've provided values elsewhere for that.
> 

Great!! 

> Somehow I don't like the 'x' icon as well as the arrow, but it does seem more logical for the functionality. I'm fine with that if you are.
> 

Is it because it's too light? I might want to make it a bit darker. I do think it's more logical – I'll let you know if I have other thoughts/ideas about it. 

> FYI, I've had some ideas about how to implement the shadow text in future — if you wanted to make an enhancement to track the idea, I'd be ok with that. However, both of my ideas are fairly complicated, so I think I'd want to see some user testing on the feedback before implementing.
> 

Yay!! Thank you!! This is one of those cases where it's more about the idea than usability – I'm not sure how much usability testing might help in this case. Some strategic usability testing would be nice though, happy to test.

**Comment by rlskoeser** [comment]
I think this is complete; you can revise the x icon if necessary or if you have a thought independent of this.
