### ISSUE TITLE
As a reader, I want to see a note in the plaintext version of an article in place of non-text content like images.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#56]
# dev notes
> I'm hoping we can come up with a way for the plain text version to include the same content that a screen reader would hear, and would love if we can leverage CSS for that as much as possible rather than adding more regexes to our plain text version (maybe if we use separate elements and associate with aria attributes?). I can see the need for regexes to add labels (roughly equivalent to what a screen reader might announce for an image), but I think we should try to keep any text replacement logic as simple as possible.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/startwords/issues/44#issuecomment-603500816_

**Comment by rlskoeser** [comment]
We merged the pull request for this feature, which Grant and Nick both reviewed, so I'm going to consider this one accepted.
