### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#58]

**Comment by gissoo** [comment]
Created 3 versions: (listed based on preference(
1. red on black 
2. black on white 
3. red on white

@Rebecca Koeser I'm fine with any of them as long as they are readable (if #1 is not readable then #2 is probably best)

They are on Drive here: Startwords > Development & Design > Assets > Favicon

**Comment by gissoo** [comment]
Note: @rlskoeser already mentioned she likes "...the red on black best! We could potentially use a different version for development (so you can easily distinguish dev from prod site in your browser bar)."

**Comment by thatbudakguy** [comment]
I agree, and I love the idea about using a different one for dev!

**Comment by rlskoeser** [comment]
@gissoo how should we get this issue closed? Should we just add the favicon to the site so we can see how it looks and confirm that our preferred choice is readable? It should be pretty easy to add.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser thanks for writing. I think that's a good idea I think. I was hoping to hear @gwijthoff's opinion on it as well.

**Comment by gwijthoff** [comment]
Red on black all the way! I definitely think it will stand out the best.

**Comment by gissoo** [comment]
@gwijthoff Great! Thank you!
