### ISSUE TITLE
As a reader, I want to see featured content on the site's homepage.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#59]
# testing notes
## designs
figma links have been updated to point at specific boards.
[mobile](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=239%3A1990) / [tablet](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=210%3A22163) / [desktop](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=819%3A16031)

## notes

there are still a few things to keep in mind here:
- we now have designs for desktop, so please test all screens!
- the _desktop_ version of the footer isn't done yet; that will be #83.
- there is one remaining differences from the current design - I wasn't able to get the red arrows next to article previews to appear in the way that they do in the design (see [slack conversation](https://cdhprinceton.slack.com/archives/CR6JCFQHE/p1586886086062600)). They are positioned relative to the titles instead. I added the slight movement behavior on hover that @gissoo and I talked about; we didn't discuss details so feel free to suggest a different interaction (or no interaction) if it looks weird.

@gwijthoff you might want to try playing around with the preview text for the two articles (using `<!-- more -->`) to get a feel for how they will truncate. the space requirements differ slightly depending on the screen - tablet is actually the most restrictive.

**Comment by gissoo** [comment]
@thatbudakguy I can't view the "homepage link" – gives me "internal error" 
Also, if this is about the homepage, could you change the figma link to show the "homepage" page on Figma? – I don't think the "Tablet" page on Figma is the appropriate one to look at

**Comment by thatbudakguy** [comment]
updated the links, thanks!

**Comment by gissoo** [comment]
@thatbudakguy 
below are my notes:
On all devices: 
1. The "read more" below the issue abstract is not matching the design, it needs to be left-aligned (aligned with the issue abstract) and slightly closer to the last line of the abstract than it is now. 
2. The "Read more about Startwords." needs to be replaced with a red arrow to match the design. 
3. The doi is missing, which needs to be below the authors. 
4. The length of the article previews need to be similar, this will be a problem that we need to fix. 
5. It will be better to have shape for the bottom of the preview text, however I don't think it's a deal breaker now, but would be nice to fix it for the next issue. 
6. I like the interaction of the red arrows! Thank you for doing this!

On mobile:
1. The "Data Beyond Vision" title is crossing the boundaries, which is causing the arrow to be misplaced as well as an increased space between the title and the authors – "Vision" should be wrapped. 

On tablet:
1. The position and width of the 1. issue number 2. issue abstract, and 3. theme do not match the designs and what was agreed. The three pieces mentioned need to match the x position of the opening paragraph on the left and regarding the width, it will need to match where the opening paragraph on the right ends, i.e. aligning with the x positions of rest of the metadata on this page.

**Comment by thatbudakguy** [comment]
ok, I _think_ I was able to address everything here. regarding the placement of the arrows when the titles wrap, it's unfortunately pretty hard to control...I was able to get it to not wrap the arrow on its own, but more control than that might be hard to accomplish.

**Comment by gissoo** [comment]
@thatbudakguy thank you! This looks great, mostly everything is fixed!

A couple of points:
regarding my earlier comment:
4. The length of the article previews need to be similar, this will be a problem that we need to fix. – Can we do something about this? 

On mobile:
1. The "Data Beyond Vision" title is crossing the boundaries, which is causing the arrow to be misplaced as well as an increased space between the title and the authors – "Vision" should be wrapped. 
- I know you have written above that it's difficult, but it looks like it's fixed! (Although I refreshed once and it was back to everything in one line, crossing the boundary, and refreshed again and it looks like it's fixed :D – not sure why this is happening) – But I think it actually matters, and visually changes the design, would be happy to discuss alternatives. (see the image)
- Same thing is happening with the DOI crossing the boundary, the two DOIs are too close to each other. (see the image)![Screen Shot 2020-04-15 at 3.20.18 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/3f62bd3d-a142-43e5-a85a-46f84a8dd16f)
- Also, sorry Nick, I just updated the DOI style here and everywhere else to match what we agreed on for the article page. Could you add "doi: ...." to be as part of the link? – You can see this in the design now.


Desktop:
1. Is there a way to prevent the featured content from increasing width on desktop and to look the same as it does on tablet?

**Comment by thatbudakguy** [comment]
@gissoo can you explain what you mean by "crossing the boundary"? in the design the preview text of the two articles are very close to each other; there's just a few pixels in between - the same as with the DOIs here.

**Comment by gissoo** [comment]
@thatbudakguy that makes sense – I think in development it looks visually even closer. I'm trying on Figma exactly what you currently have on the site, and what's on the site is so much closer, which makes a huge difference. I think one way to solve this issue is by aligning this with the design, where the left opening paragraph starts higher on the page. On the site, left and right start exactly on the same y axis.

**Comment by thatbudakguy** [comment]
ok, I've:
- added tighter margins for desktop
- pushed the second article preview down a bit to create more visual space
- added `doi:` at the start of the doi links

**Comment by gissoo** [comment]
@thatbudakguy Thank you! This looks so much better now!

Just this question:
regarding my earlier comment:
4. The length of the article previews need to be similar, this will be a problem that we need to fix. – Can we do something about this? 

(Also, just a general question that now I'm wondering about, do you know if this is the fault of Figma that there seems to be more space between the DOIs for instance, than there is on the site? – because the font size is correct) 

Otherwise I think I'm done reviewing this issue.

**Comment by gwijthoff** [comment]
I agree with Gissoo that the length of the article previews should be similar if possible, but this is more of an authorial and editorial issue than a design issue. The opening lines that have been selected for both articles right now are really good. The fact that the article on the left has more authors makes that entire block similar in size to the article block on the right with a longer preview text. At least that's a consolation, so it doesn't seem (at least to my eye) like they're mismatched now. But it might be something we want to consider for the editorial style guide, recommending a particular word limit for the opening line(s) article preview.

Also: there’s something too jagged about the article preview shapes — they don’t quite have the clean angle lines we’ve been going for. Can we experiment with word break properties to make the words conform more to the shape we’re hoping for?

**Comment by thatbudakguy** [comment]
@gwijthoff how do you feel about hyphenation to aid in keeping the shape? I turned on automatic hyphenation and increased the slope on the text-shapes, which yielded this (on tablet):

<img width="309" alt="Screen Shot 2020-04-16 at 10 13 09 AM" src="https://user-images.githubusercontent.com/4924494/79466692-eaf0ea80-7fca-11ea-9021-22244f35b109.png">

I think we might need to dynamically adjust the slope based on the screen size, because this slope becomes too steep for mobile.

**Comment by gwijthoff** [comment]
@thatbudakguy much cleaner lines! Would you mind taking screenshots of a few different options, showing the entire home page? Auto-hyphenation on and off, how both appear on mobile and tablet, etc. It would be good to get a sense of what our options are.

Not being able to shape the bottom of the lines (i.e. narrowing back down) seems to change the overall feel we were going for (@gissoo may have thoughts on this). The original design was intersecting polygons, now it's abutting triangles. So it would be good to see the range of options we're looking at right now.

**Comment by thatbudakguy** [comment]
here's some screenshot using different values for the slope of the content on mobile and tablet, with hyphenation turned on:
# mobile
<img src="https://user-images.githubusercontent.com/4924494/79492280-c2c6b300-7fed-11ea-8aa5-3f9be422399c.png" width="50%" />
<img src="https://user-images.githubusercontent.com/4924494/79492286-c4907680-7fed-11ea-92ac-63bd11b24e6c.png" width="50%" />
<img src="https://user-images.githubusercontent.com/4924494/79492292-c65a3a00-7fed-11ea-85d4-945279e51a1c.png"  width="50%" />

# tablet

![Screen Shot 2020-04-16 at 14 21 14](https://user-images.githubusercontent.com/4924494/79492863-9bbcb100-7fee-11ea-84fe-89f675f19113.png)
![Screen Shot 2020-04-16 at 14 21 20](https://user-images.githubusercontent.com/4924494/79492864-9cedde00-7fee-11ea-8723-8daa7b2dec30.png)
![Screen Shot 2020-04-16 at 14 21 26](https://user-images.githubusercontent.com/4924494/79492871-9e1f0b00-7fee-11ea-8b04-fcef45a753f4.png)

**Comment by gwijthoff** [comment]
I think I like the second option best for both mobile and tablet you screenshoot above. It's super content-dependent though — if the author or editor changes a single word in these opening lines, the shape of the polygons and the word breaks will look entirely different. But I say let's go with option two for now!

Are we waiting on anything else for this issue, or should I close?

**Comment by thatbudakguy** [comment]
@gissoo mentioned that it would be good to set an absolute limit on article preview text length, but so far I haven't been able to figure out how to do it...it looks like you can set `summaryLength` in the hugo settings, but it didn't have any effect for me.

**Comment by gissoo** [comment]
> I agree with Gissoo that the length of the article previews should be similar if possible, but this is more of an authorial and editorial issue than a design issue. The opening lines that have been selected for both articles right now are really good. The fact that the article on the left has more authors makes that entire block similar in size to the article block on the right with a longer preview text. At least that's a consolation, so it doesn't seem (at least to my eye) like they're mismatched now. But it might be something we want to consider for the editorial style guide, recommending a particular word limit for the opening line(s) article preview. @gwijthoff It probably looks better now because the left column is placed higher than the one on the right, that helps a lot :D 
> 
> Also: there’s something too jagged about the article preview shapes — they don’t quite have the clean angle lines we’ve been going for. Can we experiment with word break properties to make the words conform more to the shape we’re hoping for?

**Comment by gissoo** [comment]
@thatbudakguy thank you so much for providing these variations!!! I really like the first variation on mobile – but I do understand that the second one looks better on both mobile and tablet in this specific case. (v1 might work better in the long run – not sure). I'm not sure how I feel about the hyphenation here yet. (they do happen to be necessary evils in typography :D)

**Comment by thatbudakguy** [comment]
just wanted to mention - it's very possible to do the first one on mobile and the second one on tablet. also as you pointed out i think i have the margins wrong on tablet, so these screenshots aren't as applicable as they should be...

**Comment by gissoo** [comment]
that is great news @thatbudakguy Thank you so much!!!!

**Comment by thatbudakguy** [comment]
OK, with a little more experimenting and some...creative usage of CSS paths, I was able to create the rounded shape. Here are some screenshots for reference, showing with hyphenation turned off/turned on for mobile and tablet. The blue lines of the shaping polygon are shown for reference. We can control the height of the polygon that shapes the text, but it has to be an absolute value - unfortunately it can't scale to the size of the text itself. Currently I have 300px set, which seems to balance OK between the lengths of the two previews.

## tablet
hypens ON (left), hyphens OFF (right)

<img src="https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/c21d2f9f-6ccc-47ce-896e-1502cdfb999a" width="200">
<img src="https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/1a6b937e-c7cf-4f51-8bfa-0a427f06f3a8" width="200">

## mobile
hypens ON (left), hyphens OFF (right)

<img src="https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/4ec97248-ae51-4089-aefb-dd7c22811df2" width="200">
<img src="https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/0b6776ba-1ef5-4d75-9dab-582b56a759e0" width="200">

**Comment by gissoo** [comment]
@thatbudakguy Thank you so much for these!!! I love how these look so much more than how they currently are. I love them when there is **no hyphen**, mainly because I'm noticing that in the versions without the hyphens the words are also **not** breaking at the end of a line? Is that true? It's much more easier to read in the version without the hyphen, because an entire word is wrapped to the next line. The shape of the entire paragraph also looks much better visually in the versions without the hyphens. They especially look better on tablet than mobile. But mobile is fine too.

**Comment by gwijthoff** [comment]
This is so cool, brilliant solution @thatbudakguy! I also agree with @gissoo that the **hyphens off** version is best. There are just so many broken words on mobile that it messes with the readability. And the shapes look just as good without word breaks.

**Comment by thatbudakguy** [comment]
The shaping is still quite restrictive, and some content (including the intro for rebecca's essay) just doesn't naturally fit into the shape at all. Right now, the way I can see to implement this is:

- measure the number of characters that can reasonably fit into the shape via some trials 
- allow writers to choose the intro to their piece using `<!--more-->`, but truncate it if it has too many characters and add an ellipsis
- set an exact height for both the preview text and its outside shape so that the layout can't move around or break

this approach means that some (maybe most) previews will end up getting truncated, and it will likely require some trial and error on the part of the editor to find the right preview text. if the preview is too long it will be truncated, and if it's too short it will not fill up the shape and leave a bunch of empty space. however, the layout will be stable across various screens.

**Comment by gwijthoff** [comment]
@thatbudakguy FWIW, I don't think it's a bad idea to have that much of the editor's and author's attention on the opening lines to get them to fit perfectly. It's an interesting feature, a constraint, to have editor and author collaborate on working within that format.

**Comment by thatbudakguy** [comment]
@gwijthoff thanks, this input is helpful. based on you and @rlskoeser's comments I think I can make one or two more revisions and then we can close this out.

**Comment by thatbudakguy** [comment]
OK, I've deployed the latest version of this and updated the testing notes at the top. Would like design testing from @gissoo and a final test from @gwijthoff on fitting the article preview quotes into the new shapes.

**Comment by gissoo** [comment]
@thatbudakguy This looks amazing! Thank you for working on it!

The notes below apply to both the homepage and the single issue page.

On tablet and mobile: 
- The spacing between the article opening paragraph and the article title does not match the design (should be slightly less) (It looks very close to the design on desktop)

On all devices:
- The spacing between the article opening paragraph and the article title should be the same for both articles – currently the spacing is much more on the left side. 
- The spacing between the article title and the first author does not match the designs
![Screen Shot 2020-06-17 at 2.07.10 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/53080151-4294-4b68-ab75-85fb2a48f361)
![Screen Shot 2020-06-17 at 2.08.28 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/6c95b098-60be-43b5-b9ae-e99cc3c6068a)

On mobile: 
- The article title on the left is getting cut off:
![Image from iOS (4).png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/49aadfb9-5e77-4b31-8c97-fe54cdc800e5)![Screen Shot 2020-06-17 at 2.08.28 PM.png]

**Comment by thatbudakguy** [comment]
> The spacing between the article opening paragraph and the article title should be the same for both articles – currently the spacing is much more on the left side.

the spacing between the article preview and the article title will always be the same, since an exact height is set on the article preview text - it's just that the one on the left doesn't have enough text to fill up its container, so there is empty space in between. setting an exact height is necessary so that if there is too much text, it doesn't overflow the container.

> The spacing between the article opening paragraph and the article title does not match the design (should be slightly less) (It looks very close to the design on desktop)

same thing as above - if a preview text doesn't fill up the space (even by a few words sometimes), it will appear to create extra spacing. since the container's width changes slightly between mobile/tablet/desktop, the extra spacing will also appear to change.

> The spacing between the article title and the first author does not match the designs

I see a difference of one or two pixels, maybe...are we talking about the same thing (black square)?
![spacing](https://user-images.githubusercontent.com/4924494/84937015-22eadb80-b0a9-11ea-860d-94b12f246ec4.png)

> The article title on the left is getting cut off

I can't get this to happen when emulating an iPhone SE. Not sure how to test a solution...

**Comment by gissoo** [comment]
> > The spacing between the article opening paragraph and the article title should be the same for both articles – currently the spacing is much more on the left side.
> 
> the total distance between the top of the article preview and the article title will always be the same, since an exact height is set on the article preview text - it's just that the one on the left doesn't have enough text to fill up its container, so there is empty space in between. setting an exact height is necessary so that if there is too much text, it doesn't overflow the container.
> 

- okay then I think it might be worth to have the opening paragraph always fill the entire container height (maybe with "..." if the sentence is not completed.) The extra space is not great and is getting a lot of visual attention. 

> > The spacing between the article opening paragraph and the article title does not match the design (should be slightly less) (It looks very close to the design on desktop)
> 
> same thing as above - if a preview text doesn't fill up the space (even by a few words sometimes), it will appear to create extra spacing. since the container's width changes slightly between mobile/tablet/desktop, the extra spacing will also appear to change.
> 

- Here, I'm talking about when they **do** fill up the space, even in those cases the space does not match the design. Happy to discuss live if it will help. (should be about 31-32 px on all devices)

> > The spacing between the article title and the first author does not match the designs
> 
> I see a difference of one or two pixels, maybe...are we talking about the same thing (black square)?
> ![spacing](https://user-images.githubusercontent.com/4924494/84937015-22eadb80-b0a9-11ea-860d-94b12f246ec4.png)
> 

- It's more than 1px for sure, but not sure what the difference is. The design intended it to be about 16px. 

> > The article title on the left is getting cut off
> 
> I can't get this to happen when emulating an iPhone SE. Not sure how to test a solution...

- yes, me either.

**Comment by gwijthoff** [comment]
This looks fantastic, @thatbudakguy — thank you so much for all your hard work. This is clearly the trickiest page of the entire project! Just two additional thoughts:

The "read more" link doesn't work after the preview of the issue abstract text

Is there any way at all we can make the article opening line text shapes accommodate just a few more words? I understand you've gone over this like a hundred times but I've been playing with some edits to the text locally and RM's literally perfect line is just 35 words but the last two words cut off on mobile, reading: `When I was growing up I liked to read about dying children. I’m not talking about the Victorian orphan kind of dying either, not the dying of storybooks, but children who were` I ask because 33 words are pretty restrictive when it comes to writing punchy opening lines. Allowing for 40ish words max would probably be enough. Or even simply finding a way to fit those last two words of RM's opening lines in, and having that limit determine the length of future contributors' opening lines. We could call it the RM rule.

**Comment by thatbudakguy** [comment]
> okay then I think it might be worth to have the opening paragraph always fill the entire container height

For sure; I think this will be tricky but @gwijthoff will usually be the one who has to deal with fitting the text into that space correctly.

> It's more than 1px for sure, but not sure what the difference is. The design intended it to be about 16px on all devices. 

OK, it was hard to get this from figma - looked more like 10px to me (it always seems like Figma's line-heights are way different from the text size). I've increased it to 15px.

> Is there any way at all we can make the article opening line text shapes accommodate just a few more words?

I've added some custom breakpoints to try to carefully resize the container at a variety of different screen sizes to accommodate RM's preview text. I do not envy @gwijthoff the task of trying to come up with perfectly-sized previews for upcoming articles, but if anyone can do it, he can!

> I'm talking about when they do fill up the space, even in those cases the space does not match the design. Happy to discuss live if it will help.

This is really complicated; if there are still problems we might need to zoom. Let me know how it looks to you with the latest changes.

**Comment by gwijthoff** [comment]
@thatbudakguy that fully fit RM's opening lines into the homepage preview on mobile for me. Nice work.

**Comment by gissoo** [comment]
@thatbudakguy This looks great!! Thank you so much for all of your work!!

**Comment by gissoo** [comment]
> > okay then I think it might be worth to have the opening paragraph always fill the entire container height
> 
> For sure; I think this will be tricky but @gwijthoff will usually be the one who has to deal with fitting the text into that space correctly.
> 
> > It's more than 1px for sure, but not sure what the difference is. The design intended it to be about 16px on all devices.
> 
> OK, it was hard to get this from figma - looked more like 10px to me (it always seems like Figma's line-heights are way different from the text size). I've increased it to 15px.
> 

- @thatbudakguy it looks much better now!

> > Is there any way at all we can make the article opening line text shapes accommodate just a few more words?
> 
> I've added some custom breakpoints to try to carefully resize the container at a variety of different screen sizes to accommodate RM's preview text. I do not envy @gwijthoff the task of trying to come up with perfectly-sized previews for upcoming articles, but if anyone can do it, he can!
> 

- @gwijthoff yes, please!! 

> > I'm talking about when they do fill up the space, even in those cases the space does not match the design. Happy to discuss live if it will help.
> 
> This is really complicated; if there are still problems we might need to zoom. Let me know how it looks to you with the latest changes.
>

- @thatbudakguy I think this is happening on my phone because of the "The article title on the left is getting cut off" screenshot I had attached earlier, above, _I think_. It's fine on desktop and tablet.
