### ISSUE TITLE
Revise pdf designs by visually communicating specs + showing other variations of margins that are less preferred varieties

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#70]

**Comment by rlskoeser** [comment]
@gissoo here's a PDF of a draft article that's been generated with print CSS and WeasyPrint. It's basically an initial stab at the basics, like margins, fonts, and headers and footers. The main article page isn't fully implemented and styled yet, and the PDF depends on that.

I'm not sure I'm getting the correct font sizes from Figma for the header (e.g., the font size for the  article title in the top left running header doesn't look right to me). 

I was wondering if you could revise the margin placement in your design to make it easier to translate into page properties? Because the margins on the header/footer content don't match the margins in the body content, I need to use a combination of page margins and margin or padding on the body content to get the right layout - this is fine! But I want to make sure I'm doing it correctly.

Also, I wondered if there is a way for you to provide margin sizes in inches or cm (or can I get it from Figma)? I don't know how much it matters, but it feels more natural to me than using pixels for working on something to be printed.

[dbv.pdf](https://github.com/Princeton-CDH/startwords/files/4505557/dbv.pdf)

**Comment by gissoo** [comment]
> @gissoo here's a PDF of a draft article that's been generated with print CSS and WeasyPrint. It's basically an initial stab at the basics, like margins, fonts, and headers and footers. The main article page isn't fully implemented and styled yet, and the PDF depends on that.
> 
> I'm not sure I'm getting the correct font sizes from Figma for the header (e.g., the font size for the article title in the top left running header doesn't look right to me).
> 
You're right, I'm identifying and comparing the font sizes in "Edit PDF" with the font sizes on Figma and they are not correct – All the text in the header and the footer must be 11 points but they are currently 8.25 (The header is "IBM Flex Serif" and the footer is "Source Sans Pro" – in the PDF they are times new roman, I can't remember if we had this discussion about print specifically, should the fonts be different or can we use the same fonts that we have?) 

according to the designs, 
- the "issue 1" must be size 14, but it's currently a 9. 
- the "TRANSFORMATIONS" must be size 16, but it's currently 12. 
- the "Data Beyond Vision" must be size 16, but it's currently 12. 
- the author names and the date must be size 14, but they are currently 9.
- the body text must be size 12, but it is currently 9. 

The body text looks right though – I don't know how much to trust all of these numbers! This is a bit weird (again potential issue with Figma) 


> I was wondering if you could revise the margin placement in your design to make it easier to translate into page properties? Because the margins on the header/footer content don't match the margins in the body content, I need to use a combination of page margins and margin or padding on the body content to get the right layout - this is fine! But I want to make sure I'm doing it correctly.
> 
Do you mean the margins of the header and the footer must align with the margins of the body? I'm not quite sure I understand what aspect of their placement I should revise, should I add guides to visually help it?  
> Also, I wondered if there is a way for you to provide margin sizes in inches or cm (or can I get it from Figma)? I don't know how much it matters, but it feels more natural to me than using pixels for working on something to be printed.
> 
After we discussed yesterday I searched more and I still can't find a way to change sizes to inches or cm, I can totally do it by hand! I think it's worth it for now.  
> [dbv.pdf](https://github.com/Princeton-CDH/startwords/files/4505557/dbv.pdf)

**Comment by gissoo** [comment]
@rlskoeser just to start something on this while I wait for your responses, I converted the measurements for margins and added them [here on Figma page for PDF](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=164%3A1321) I can revise them so they can be as round as possible in inches.

**Comment by rlskoeser** [comment]
Thank you for the measurements on Figma! That will be helpful. I don't know how much it really matters if they are round sizes in inches... what do you think? Are the margins for the current layout (using pixels) accurate?

I thought the header/footer fonts looked small! How are you investigating the PDF to determine what sizes and fonts they are? 

I think we _should_ be able to use the same fonts (if we want to); I wasn't sure how to tell what fonts it was using.

Weasyprint has a default stylesheet that I think is being applied - it has some useful things (like autogenerating bookmarks based on headers), but I wonder if it's applying styles we don't want. I can investigate that more when I return to this.

**Comment by gissoo** [comment]
> Thank you for the measurements on Figma! That will be helpful. I don't know how much it really matters if they are round sizes in inches... what do you think? Are the margins for the current layout (using pixels) accurate?
> 
I'm not sure either – just seemed natural to me to make them round but not sure if it matters at all
do you mean are they accurate on the pdf? – I don't have a way to check that – I can probably use an adobe design tool to check it – I'll let you know
> I thought the header/footer fonts looked small! How are you investigating the PDF to determine what sizes and fonts they are?
> 
I open the pdf with adobe acrobat and then go to "Edit PDF" and then select the text and it shows me all of its properties on the right. 
> I think we _should_ be able to use the same fonts (if we want to); I wasn't sure how to tell what fonts it was using.
> 
> Weasyprint has a default stylesheet that I think is being applied - it has some useful things (like autogenerating bookmarks based on headers), but I wonder if it's applying styles we don't want. I can investigate that more when I return to this.

**Comment by rlskoeser** [comment]
@gissoo thanks for adding the boxes to make the margins and spacing more clear, and for providing more options..

I think margin v1 is the best.  Unless you want to round up the numbers and adjust the spacing, I don't think it makes sense to use the sizes in inches. I can stick with pixels, but I will need you to help me test the layout and placement (but I would need that anyway!).

I'm with you: I don't like the one where the header and footer margins match the page margins either.

I also what you mean about the one where the header and footer are the same size. I don't think there's any reason they need to be the same size.

**Comment by gissoo** [comment]
@rlskoeser Sorry just seeing this! Great! Thanks for looking, yes looking forward to testing it!! 
Also, I just read my earlier comment here, I had said "do you mean are they accurate on the pdf? – I don't have a way to check that – I can probably use an adobe design tool to check it – I'll let you know" – sorry had forgotten to do this. I just compared the margins of the PDF with the designs on Figma for v1, and they don't match: 
- So the paragraphs should be 107px away from each side ([shown as the red boxes on this figma page](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=659%3A57)) but on the PDF you have shared those spaces are each 81px. 
- Also, the logotype on the first page should be 21px away from the top and the logo on the other pages should be 19px away from the top, but right now they are respectively about 9.3px and 9.1px away from the top. 
- The page number should be 20px away from the bottom of the page, but on the pdf that space is about 13.65px. 
- The logotype and the logo and page numbers should be 20px away from the edge on the right, as also shown by the pink boxes in the link above, however in the pdf that space is 16px. 

I hope these help. These might be solved when the header and footer dimensions are fixed, but thought may be helpful to point them out here as well.

**Comment by rlskoeser** [comment]
@gissoo thanks for all the feedback, this will be very helpful when I circle back to the PDF styles and I think the revised pdf designs are sufficient. Should I close?

**Comment by gissoo** [comment]
@rlskoeser Sure!
