### ISSUE TITLE
Place all styles for active and non active states on one page on Figma

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#72]

**Comment by gissoo** [comment]
@rlskoeser Does this help by any chance? I put all of them here: 
(https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=688%3A1772)

**Comment by rlskoeser** [comment]
I think might be better for @thatbudakguy to weigh in, I haven't worked with these link styles as much. It kind of looks to me like none of the link styles change in the other modes, although I know the red `>` moves slightly.

Unrelated but reminded by seeing it: can we make the doi on mobile home page and issue list a smaller font so it doesn't wrap? Or how important is it to include on that page? I find the look of the doi distracting.

**Comment by gissoo** [comment]
- @rlskoeser @thatbudakguy Yes, you're correct, except for the red arrows none of them change (I don't think any change is necessary with the text links). Although I just commented on Figma and asked Nick what he thinks about the purple arrow to also move slightly. 

- @rlskoeser the doi is 16 on figma, which is the smallest it should really be on mobile. I think we agreed to have it display on the home and the single issue pages. For it to not wrap it will need to be much smaller in which case I don't think it should even exist on the page, @gwijthoff happy to hear if you find the doi necessary or not on the home and the single issue pages.

**Comment by rlskoeser** [comment]
Thanks for clarifying @gissoo and explaining about the doi. I think we did agree to display them. I didn't recognize how small it already is; if it's too small to be readable there's no point in having it there. I defer to @gwijthoff on the importance of including them.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff 16 is still readable but anything smaller is not recommended for readability.

**Comment by gissoo** [comment]
@rlskoeser re arrow behaviors: Nick reminded me that we had already talked about applying the red arrow behavior (how it slightly moves on hover) to the purple arrow on the single issue page as well, I had totally forgotten!

**Comment by gwijthoff** [comment]
I agree that it would be nice if the DOIs didn't wrap, but their font does seem as small as we should make it. The argument for including the DOIs on the homepage is to signify that this is a scholarly publication. So, I suppose we keep it the way it is, unless there's a way of shortening a Zenodo-generated DOI.

**Comment by gissoo** [comment]
@gwijthoff thanks for writing! This makes sense to me. I'll wait for @rlskoeser and @thatbudakguy to weigh in before taking any action on this.

**Comment by thatbudakguy** [comment]
fine with keeping the DOIs the way they are, but also fine with not having them on the homepage.

**Comment by rlskoeser** [comment]
I'm fine with keeping the DOIs. Maybe for future issues we'll be able to use Princeton-minted DOIs (although IDK if they'll be any shorter).

Thanks @gwijthoff for reminding us why we decided to put them there.

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff Thanks for writing. I think we can close this issue, since it's a chore and doesn't need formal review.
