### ISSUE TITLE
Add guidelines for placing images inside the contextual note container

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#73]

**Comment by gissoo** [comment]
@rlskoeser [here are the guidelines](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766), please let me know what you think

**Comment by rlskoeser** [comment]
@gissoo these look great to me. Is the white arrow at the bottom to indicate the bottom margin/padding?

**Comment by gissoo** [comment]
@rlskoeser yes, that space will always apply.

**Comment by gissoo** [comment]
@thatbudakguy @gwijthoff Please take a look at this issue and share any thoughts you may have about it.

**Comment by gwijthoff** [comment]
I might not be understanding the function of your diagram here, but a question about the min width screen with two boxes stacked vertically on top of each other: why wouldn't those two images be placed horizontally, side by side?

**Comment by gissoo** [comment]
- @gwijthoff Thanks for looking, I'm just trying to communicate the basics with margins of images inside the container – [like this one that was discussed here](https://docs.google.com/document/d/1VYO8qgLAld0tJ-NCNz47bMOWvS_URLFc9lYqaiqr8gc/edit?disco=AAAAGWh0bGg)

- Thank you for pointing this out!! I always like the idea of putting two images next to each other however it will work best if the two images have the same width and height – and I'm not sure how often this will be the case – but I think it's important for it to be covered here @rlskoeser what do you think? Ok to revise and add more conditions to the guidelines? 

- also, not sure if the images will need captions?? @rlskoeser – This might complicate things a bit, will need to consider when revising the guidelines

**Comment by rlskoeser** [comment]
If we don't have a need for side by side images in contextual notes I don't think it should be MVP, but I could imagine having that later on.

I think images in contextual notes should _not_ have captions.

**Comment by thatbudakguy** [comment]
these look good. I have the same question as grant - in the mid width mobile/tablet versions the images seem incredibly small. do we need so much margin?

**Comment by gissoo** [comment]
@thatbudakguy Thanks for writing! I see your point. 
So the minimum image allowed should be larger? It's not about the margin, it's about the image, the quality of the image should also be good enough, basically if I increase the min size it means the image quality should also be higher.

**Comment by gissoo** [comment]
> If we don't have a need for side by side images in contextual notes I don't think it should be MVP, but I could imagine having that later on.
> 

- So do you think it's worth investigating designs now? Or later? 

> I think images in contextual notes should _not_ have captions.

- I agree, thanks!

**Comment by thatbudakguy** [comment]
according to figma, the image width is less than 100px - I have a hard time imagining what kinds of images are legible at that size, unless they're more like icons. conversely, it's pretty trivial to obtain a version of any image we want to show of at least 200-300px wide, so i don't think we will have quality problems - if anything we'd be downscaling, not upscaling. does that make sense?

**Comment by gissoo** [comment]
@thatbudakguy Yes, I was imagining the use of non-vector icons too, sorry that wasn't explicit. Agreed, probably better to increase the min and make sure the image quality is good (should be incorporated into the review/editorial process) – will revise and put back for review again

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff  [I have revised the guidelines](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=153%3A2766) to be more specific. 
What are your thoughts now?

**Comment by rlskoeser** [comment]
@gissoo Thanks for revising these. I'm sorry, but I'm not sure what all the variations are meant to be communicating.

What is the difference between images and icons? Why do we need to distinguish them?

I don't think we need side by side images, it's hard to imagine it being useful. We could always combine two images into a single image for display in a contextual note.

**Comment by gissoo** [comment]
@rlskoeser Did you see the "frame"/canvas labels? The label are supposed to help. I organized the variations a bit differently in case it helps.

The max and min widths for icons are less than the max and min widths for images – this is important because an icon does not need and should not be as large as an image (maybe I should call it "photos" instead of "image") – icons are most often easy to read when not large (that is their purpose) – it is unnecessary for them to be as large as a photo – not only it's unnecessary in that it's visually awkward, but also it's unnecessary in that it increases the length of the contextual note container. I know we may not be using icons inside the container right now, but I think it's important to communicate that the distinction matters a lot.

**Comment by rlskoeser** [comment]
@gissoo I think this is enough detail to implement the styles.  It seems like there is some redundancy — it looks like the image sizes on desktop, tablet, and mobile are all the same. Am I missing something? 

Thanks for explaining about the icons. Do you think we need to implement and test styles for icons in the short term? Or could we document and add later?

I think we can probably close this, but I wonder if this is the most efficient way to document/share this information for future.

**Comment by gissoo** [comment]
> @gissoo I think this is enough detail to implement the styles. It seems like there is some redundancy — it looks like the image sizes on desktop, tablet, and mobile are all the same. Am I missing something?
> 

- You're right. They are the same, I have to show them to communicate that they are the same, otherwise it'll turn into a vague and unclear situation that I don't like. Can you easily check the dimensions? Or is Figma being totally useless about it in this case as well? (Trying to find a happy medium where I'm specific enough but not redundant, don't want to write too many notes, e.g. of the dimensions of shapes if it's possible to avoid, happy to hear your thoughts)

> Thanks for explaining about the icons. Do you think we need to implement and test styles for icons in the short term? Or could we document and add later?
> 

- I think it's fine to document and add later – more iterative that way to me

> I think we can probably close this, but I wonder if this is the most efficient way to document/share this information for future.

– Agreed. This will get lost and forgotten unless I come and find the comments. The designs will remain on file with a bit of a distance and some notes. Google doc needed in this case??

**Comment by rlskoeser** [comment]
@gissoo I am able to see the sizes in Figma. In this case, when the container is the same width on all devices it seems like you could document with a note that images are the same for all screens. But I agree it's important to be explicit about that.

I think this is complete, I'm going to go ahead and close.
