### ISSUE TITLE
Create styles for pull quotes

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#74]

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy @gwijthoff [please take a look at the designs here](
https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=865%3A11098). 
There are 3 main versions I designed (Let me know if you have other thoughts/suggestions) – I want to keep this simple and just make it stand out by using parts of the logo in it as quotation marks. I don't want to use the polygon that's used in the footer or the contextual notes, I tried it and it diminishes the uniqueness of that polygon when used in more places. (I like the grey version more, it's just cleaner and less boxy). 

Note: Figma does not have text wrapping capabilities for me to properly mock this. However, I have created a stroke/outline for the containers which represents the distance (negative space) between the text and the container.

I'm pretty flexible with this, just a few conditions: 
1. The pull quote container should not be placed in the middle of the paragraph on desktop and tablet, because the column is already too narrow to fit a pull quote. As I have shown, it would be better if it is placed either on the left or the right side in the paragraph. 
2. On mobile, I think the container should be centered and take the entire width of the screen. I don't see how it will work any other way. 

Should I define a min/max height and width for the container for tablet and desktop?

**Comment by rlskoeser** [comment]
@gissoo I like the main version a lot! (The first three screens that I see when I open the link — they don't have versions or numbers.) I like it much better than all the other variants.

1. Would it always be on one side (left only / right only) or would you suggest having an option to vary it?

Defer to @thatbudakguy on specifics — I think we need the width for tablet/desktop in terms of grid or percentages. I guess a min-height would be useful if we might have short quotes, but I don't think we can set a max height since it will depend on the content.

**Comment by gissoo** [comment]
> @gissoo I like the main version a lot! (The first three screens that I see when I open the link — they don't have versions or numbers.) I like it much better than all the other variants.
> 

@rlskoeser thanks for writing. Sorry I wasn't being explicit. The first three screens are just created to show you how one version might look like on all devices, and I picked my favorite to show that :D ... I'm glad you like that one too. 

>     1. Would it always be on one side (left only / right only) or would you suggest having an option to vary it?
> 

So in all of the examples I provided I have shown both left and right on all screens to mean that both would be possible at the same time. Is that what you are asking about "an option to vary it"? 

> 
> Defer to @thatbudakguy on specifics — I think we need the width for tablet/desktop in terms of grid or percentages. I guess a min-height would be useful if we might have short quotes, but I don't think we can set a max height since it will depend on the content.

That makes sense, thank you. I'll wait to hear from @thatbudakguy on this.

**Comment by thatbudakguy** [comment]
I like v1a and v3a, but would be happy with any of the a-versions.

Expanding on @rlskoeser's note about placement, I'm not sure if there's a way for the writer to indicate whether they wanted the quote to appear on the left or the right (markdown class?). It's easy for us to make them all one side, though. There _might_ be a way to automatically alternate them (thinking something funky with `nth-of-type`).

Complicating this a bit is the fact that there's no way to indicate quote attribution (usually the `<cite>` attribute in a `<blockquote>`) in pure markdown, so to get a style that differentiates them, the writer (editor?) would need to be writing a little html to format the quote anyway.

One thing I noticed is the usage of purple for the quote text and attribution in all of the "a" versions. Purple is our link color, so I'm worried that people will interpret the entire blockquote as an interactive element or large link.

Regarding @rlskoeser's comment on sizing:
>Defer to @thatbudakguy on specifics — I think we need the width for tablet/desktop in terms of grid or percentages. I guess a min-height would be useful if we might have short quotes, but I don't think we can set a max height since it will depend on the content.

I agree, I think we will want to set a width for quotes on all screen types in terms of our existing grid (say, 2 or 3 columns). It will of course change based on the screen type. I tried turning on the layout grid for these screens in zeplin but didn't see any - @gissoo does that sound OK to you?

**Comment by rlskoeser** [comment]
@thatbudakguy yes, I was thinking markdown class. Also thinking we might want to do a shortcode so we have an easy way to do a figure with blockquote & attribution (or whatever the right semantic markup should be). Seems better to specify than complicate the css and automatically alternate them, although I guess just using even/odd wouldn't be that hard...

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser thanks for writing. Yes, this is helpful

> I like v1a and v3a, but would be happy with any of the a-versions.
> 

I'll wait to hear from Grant, also, but I am leaning strongly towards v3a.

> Expanding on @rlskoeser's note about placement, I'm not sure if there's a way for the writer to indicate whether they wanted the quote to appear on the left or the right (markdown class?). It's easy for us to make them all one side, though. There _might_ be a way to automatically alternate them (thinking something funky with `nth-of-type`).
> 

I think it would be nicer if they could be positioned left and right to create some dynamics on the page. Although, for a first version I'm not too concerned about it if it's too difficult to think about right now. 

> One thing I noticed is the usage of purple for the quote text and attribution in all of the "a" versions. Purple is our link color, so I'm worried that people will interpret the entire blockquote as an interactive element or large link.
> 

@thatbudakguy Don't worry about this. You're right, the color is the same as the color for links (there is a lot of purple on the site in general as it's part of its identity), however, the 1. typeface, and the 2. thickness and the type style are different from the style of a link. (it's Source Sans Pro, and it's in italic and bold) – so it's different enough from a link style and I think it's appropriate. 


> I agree, I think we will want to set a width for quotes on all screen types in terms of our existing grid (say, 2 or 3 columns). It will of course change based on the screen type. I tried turning on the layout grid for these screens in zeplin but didn't see any - @gissoo does that sound OK to you?

Yes! Totally, will do this soon, and will make sure the layout grid is on when I show it to you next time, sorry had to turn it off and forgot to turn it back on.

**Comment by gwijthoff** [comment]
Hi @gissoo, this looks great — I too was drawn to v3a before I even read that it's the one you favor, so I'm glad we're already in agreement. I also really like the way you differentiated author names and publication date in the article header. 

@thatbudakguy typically the editor is the one who selects pull quotes from an article, not the author. It can be hard for an author to know what the most salient or interesting parts of their writing is to a reader. We can of course let authors know in the style guide that they can suggest pull quotes to the editors, but I don't think you need to worry about working within markdown conventions so that authors are able to block off their own pull quotes.

**Comment by thatbudakguy** [comment]
> typically the editor is the one who selects pull quotes from an article, not the author.

totally makes sense. I had it in my head that we should be reducing as much as possible the amount of manual editing necessary, but I didn't know how much editors normally do! I think assuming that the editor has a large amount of control over the markdown representation (including editing some html where necessary) frees us from a lot of complexity in other parts of the site, as with the homepage previews.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy based on the very last bullet in my last comment as well as what we all agreed on [here is a revised version of the pull quotes](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=865%3A11098) 

- I have turned on the layout grids and as you can see adjusted the width of the pull quote containers so that on tablet and desktop the container is **always taking half of the width of the paragraph**. On mobile **it will need to be full-width at all times**. (which would mean that it will be full-width till the width of the screen exceeds 414px, then it will follow the size specified on the tablet, is that correct @thatbudakguy?) I think the widest mobile screen is 414px, I may be wrong)

**Comment by gwijthoff** [comment]
@gissoo looks phenomenal! I think this can be closed if others approve

**Comment by thatbudakguy** [comment]
yep, looks great! I'm good to go on this too.

@gissoo the largest mobile device is 767px, which is one pixel less than tablet. same thing for all breakpoints: they go from one pixel larger than the previous breakpoint, to one pixel smaller than the next breakpoint.

```sass
$breakpoint-xs: 320px;
$breakpoint-s:  768px;
$breakpoint-m:  1024px;
$breakpoint-l:  1280px;
$breakpoint-xl: 1440px;
```

so "xs" is technically 320-767px, "s" is 768-1023px, etc.

**Comment by rlskoeser** [comment]
Looks great to me too!

**Comment by gissoo** [comment]
@thatbudakguy I wrote that first ...close I was thinking 768!! ...and then I got it mixed up with the idea of 414px ...thanks for clarifying.

@rlskoeser @thatbudakguy is there a way to make sure this can be a bit more customizable in the future? From a design point of view having a pull quote be full-width in the middle of a paragraph on screens wider than 414px is not ideal, it's kind of awful. Just imagine if that's happening on a screen like the tablet here.

**Comment by thatbudakguy** [comment]
sure, we could do:

- no larger than 320px for mobile and tablet
- 50% of the paragraph for all other screens

does that sound good?

**Comment by gissoo** [comment]
@thatbudakguy I'm not sure. Do you mean always 320px for mobile and tablet? (Because I don't think narrower will be readable enough). That will help tablet-like sizes [(as you can see here I am testing it](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=923%3A40)), but I think that will be awful for screens that are 414px, for instance, because the paragraph is only a little bit wider than the pull quote and there may be words/letters coming before or after the pull quote, [look here, I am testing with a 414px screen. ](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=923%3A640)

**Comment by thatbudakguy** [comment]
I think we're getting a little into the weeds here; it's my fault for being pedantic. The 414px number comes from the fact that it's the largest _actual_ mobile device width that I know of; the iPhone XS Max and Galaxy Note 9 are both this size. So, we have to call the sizes between 415px and 767px "mobile" (since they're too small for tablet), but it's unlikely that anyone would ever actually view the site at that resolution.

@gissoo are you OK with pull-quotes being full-width for all devices below 768px, with the knowledge that almost certainly nobody will ever actually _see_ them be larger than 414px?

**Comment by gissoo** [comment]
@thatbudakguy thanks for writing, yes :D I'm OK with it, that would be a better option, thanks for clarifying.
