### ISSUE TITLE
Design the issue list page for desktop 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#77]
Note: the font sizes for desktop are new. (sized up by 2 pixels from mobile/tablet, except for the large THEME text on the issue list page, which has been sized up by 10 pixels from mobile/tablet).

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff @thatbudakguy [Please take a look at the design here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=819%3A18470) and let me know what you think.

**Comment by rlskoeser** [comment]
The longer wrapped version of the issue theme on desktop doesn't look as good to me (more accidental than intentional, maybe?), but I know you and @thatbudakguy had some discussion about the implementation — I defer to you two.

Otherwise, this seems fine to me.

**Comment by gissoo** [comment]
@rlskoeser thanks for writing! I totally agree! I wanted to make sure my logic for desktop is logical and consistent everywhere, otherwise I prefer it if the width of the content here is just like the tablet and mobile versions (narrower). I defer to @thatbudakguy though.

**Comment by thatbudakguy** [comment]
I agree with @gissoo, it's nice to not have to resize the container. Would've missed the font size changes here unless @rlskoeser had tipped me off, but it looks great! I'm very happy with it.

**Comment by rlskoeser** [comment]
@thatbudakguy @gissoo I'm confused, it doesn't sound like you are agreeing. Or am I not understanding?

@thatbudakguy why is it hard to keep the theme word breaking at the same size across screens? (Feel free to point me to wherever this conversation happened before.)

**Comment by thatbudakguy** [comment]
the container that limits the size of the theme word isn't absolutely sized; it's sized according to the grid, which scales to fit the screen. the designs as shown above would keep the container set at the same grid column span, so there would be no need to write new code.

the relevant discussion is starting from https://github.com/Princeton-CDH/startwords/issues/17#issuecomment-637048499; @gissoo and I agreed that it was simplest to allow the grid columns to fit the screen, which will result in some dynamic resizing of content on the grid.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser thanks for clarifying, I got confused too. Thank you for writing! Yes, we had agreed on this, and I think it's a good place to compromise, I don't find it as important to focus on as other matters with the contextual note UI and interaction, for instance. 

@thatbudakguy @rlskoeser  I have now explicitly added to the "description" section on all the desktop design issues a note about the change of the font size for desktop, hopefully it will be helpful. I did it in a very systematic and clean way for all the pages (based on the sizes on mobile/tablet) so it should make sense. Please let me know if you have questions.

**Comment by gwijthoff** [comment]
@gissoo as long as the Figma link above represents the finished version you're all discussing, I really like the way the word breaks within that container. This one is Strategist Approved™️!

**Comment by gissoo** [comment]
Okay if everyone is fine with this issue, can we close it? @rlskoeser @thatbudakguy? Grant is fine.
