### ISSUE TITLE
Design a footer for desktop

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#80]

**Comment by gissoo** [comment]
I have created the same footer for desktop. @rlskoeser I have updated the font and the size of the icons here because they were too small. Is this ok with you? I still have to create a text style for the "About" text for desktop footer.

**Comment by gissoo** [comment]
Note: Decided this is a design chore since the design has already been agreed upon.

**Comment by rlskoeser** [comment]
This seems fine — and logical — to me. Not sure why you're tagging me, did you mean to tag @thatbudakguy ?

**Comment by gissoo** [comment]
@rlskoeser thanks for writing. Sure, sorry don't know why I thought you're working on this. @thatbudakguy what do you think about this? Are you okay with my first comment?

**Comment by thatbudakguy** [comment]
looks good to me - I think this is already implemented, since the footer already scales in the way that's shown here. happy to not have to revisit it!

**Comment by thatbudakguy** [comment]
closing since i think we all agree and there's no more work to do here.

**Comment by rlskoeser** [comment]
@thatbudakguy do the icons and font sizes already scale up?

**Comment by thatbudakguy** [comment]
oh, good catch! I didn't notice that. I'll make an issue to track the adjustment.
