### ISSUE TITLE
Implement footer design for desktop

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#83]
# testing notes
I think this really only needs :eyes: from @gissoo to confirm that the scaling looks right.

# dev notes
- [x] scale up link list font size
- [x] scale up icon links

**Comment by gissoo** [comment]
@thatbudakguy would you please check [the footers here ](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=331%3A204)? I think the angle of the footer triangle is not correct. The placement of the content inside the triangle right now doesn't match the design (it might be only a couple of pixels).

**Comment by thatbudakguy** [comment]
ok, I've:
- adjusted the font size slightly
- made the right part of the triangle slightly longer
- readjusted the positioning of the content

**Comment by gissoo** [comment]
@thatbudakguy this looks great, thank you!

**Comment by gissoo** [comment]
@thatbudakguy sorry just noticed this happening everywhere on Safari desktop :[
![Screen Shot 2020-06-17 at 4.29.13 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/23dfaf98-1950-429f-af50-65c21896f48b)

**Comment by thatbudakguy** [comment]
whoa!!! I'll see what I can do about that, good catch!

**Comment by thatbudakguy** [comment]
ok, I think I've resolved this with a vendor prefix - give it another look.

**Comment by gissoo** [comment]
@thatbudakguy this is fixed! Thank you.
