### ISSUE TITLE
As a keyboard user, I want to see a visual focus indicator so I can easily navigate around the site.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#85]
# testing notes
design was tracked on #71.

there are a few slight differences from the designs - notably the footnote marker - but I got as close as I could while still going for something that looked reasonable. overall the site _is_ tab-navigable, but there are a few confusing things that are beyond the scope of this issue to resolve (e.g. management of focus when contextual notes are opened/closed). the experience may not be perfect now, but I think it merits revisiting later if at all.

**Comment by gissoo** [comment]
@thatbudakguy 

With keyboard
- I'm trying to see the visual focus indicator when using the keyboard (tab) (tried various combinations) but can't get to any of the links on the pages of the site on Firefox and Safari. It is only working on Chrome. 

With mouse
- The visual indicator on Chrome and Firefox appear when selecting the links with the mouse. No visual indicator appears on Safari even with the mouse. 

CHROME
- There is no visual indicator for the "About" section on the homepage, and the startwords and the cdh logos in the footer on Chrome though.

**Comment by thatbudakguy** [comment]
whoops, I should have given instructions! sorry about that.

you have to turn on the ability to use tab to navigate for both safari and firefox. [take a look at this article](https://www.webassign.net/manual/student_guide/t_a_osx_tab_config.htm).

there used to be no way to differentiate between tab-focusing and clicking an element in css, which is why the focus ring would still show on click, but I just found out about `:focus-visible`, so I tried it. unfortunately it doesn't seem to do anything in any of the browsers I tested (the style just doesn't display on focus), so I guess we have to live with the style showing on click for now. [here's what I was reading](https://css-tricks.com/keyboard-only-focus-styles/) to implement that - @rlskoeser may be interested to take a crack at it too. apparently `:focus-visible` is now preferable to `:focus` in most instances, but it didn't work for me...

@gissoo let me know when you test after following those instructions; I think it will affect all browsers.

**Comment by gissoo** [comment]
Thanks, @thatbudakguy this is so helpful! 

With keyboard
- Right now there is no visual indicator for the startwords and the cdh logos in the footer on Chrome, FF, and Safari. 

- The visual indicator for the "About" section on the homepage is not showing on Chrome and Safari, only shows up on FF. 

- Also, just thinking about this now, shouldn't we have this capability for the nav as well? 

- Regarding the indicator showing up on click, I don't think it matters that much from my perspective.

**Comment by thatbudakguy** [comment]
ok @gissoo, thanks for the thorough review last time - this is ready for another look.

- I've added visual focus indicators for the two footer icons that didn't have it (they are slightly wacky shapes, and different on every browser, but I don't see a way around that at the moment).
- I added a visual focus indicator for the "about" section on the homepage for all browsers.
- I added a visual focus indicator for the main nav (good catch!), let me know what you think...it's supposed to be subtle but hopefully will do the job. I can tinker more with it if necessary, but it's really tough to add things like outlines because these buttons are shaped and rotated in a special way.

**Comment by gissoo** [comment]
@thatbudakguy thank you!!! This looks great! I have checked everything you mentioned and it's all fine. 
The visual indicator for the main nav looks great!! Can we make it a bit thicker/the white to be thicker? It's too subtle to the eye, if we can thicken the white it would be perfect!

**Comment by thatbudakguy** [comment]
@gissoo OK, I've doubled the size of the white border to 4px. if it looks good to you, go ahead and close the issue.

**Comment by gissoo** [comment]
@thatbudakguy thank you!! Looks so much better!!
