### ISSUE TITLE
On mobile, large contextual note containers are not fully within view (exceed the height of the page)

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#92]
@rlskoeser I am looking at this. I think:
- As you mentioned about the angle, I'm not sure if the angle is correct, but I know the right side of the polygon (top) is longer in my designs and it's shorter in the implementation (i.e. the right of the x button). 

- What have you defined the max height to be? I think I had defined a min, I'm not sure about the max.

**Comment by rlskoeser** [comment]
@gissoo about the height: I set the max height for the full note to `468px` based on what I saw in Figma (although I now see it isn't labeled as a maximum). Weirdly, the browser doesn't seem to respect this max-height; footnote 5 actual height in my browser is 479px. I _think_ the full height of the note is based on the paragraph height, which I have set as `275px` based on the same Figma design (and this is my puzzlement, that those sizes don't come out right!). Looking again, I think maybe the text of the note is starting lower than in your designs ... and I'm not sure what is controlling the position! I could try to move it up some - maybe 20px?

**Comment by rlskoeser** [comment]
Ok, I downloaded the contextual note shape from Figma and set it as the background of an actual note, and set the CSS background to blue so I could see the difference. You're right, it is slightly off!  I can't remember how I calculated this originally, Figma doesn't let me inspect the shape. I don't know how to read the path in the SVG well enough to convert it to the CSS polygon notation, and I just looked again and don't see any tools that will do it for me.

Here's the clip-path polygon I'm currently using for the shape:
`clip-path: polygon(calc(100% - 70px) 0, 100% 42px, 100% 100%, 0 100%, 0 107px);`

Do you want to suggest a revision based on the image in your design files? I presume you can provide the dimensions I need that I can't get from Figma. (Alternatively, I could try tweaking it so it matches the image I downloaded from Figma.)

![Screen Shot 2020-06-23 at 12 02 03 PM](https://user-images.githubusercontent.com/691231/85427208-72b62080-b549-11ea-95a9-c1068aef534a.png)

**Comment by gissoo** [comment]
@rlskoeser sure, just so I know which one did you download? Could you send me the direct link to it on Figma? It might help just in case

**Comment by gissoo** [comment]
> @gissoo about the height: I set the max height for the full note to `468px` based on what I saw in Figma (although I now see it isn't labeled as a maximum). Weirdly, the browser doesn't seem to respect this max-height; footnote 5 actual height in my browser is 479px. I _think_ the full height of the note is based on the paragraph height, which I have set as `275px` based on the same Figma design (and this is my puzzlement, that those sizes don't come out right!). 
>

- Thanks for writing. Sorry about the confusion, it's misleading ...the intent for those three screens were inconsistent ...I'll need to revise how they are laid out ...Can we set the max height to 379px? I think that might make more sense. 

- Looking more at how this looks when the note inside it scrolls, I think it makes more sense for me revise the spacing I had defined, it's too tight. I think it's 71px from the bottom of the text to the bottom of the container. Can we reduce the spacing to 45px? (FWIW, this way the max text container inside the note container is 203px.)

>Looking again, I think maybe the text of the note is starting lower than in your designs ... and I'm not sure what is controlling the position! I could try to move it up some - maybe 20px?
>

- Yes, I think in the designs it starts higher. Just tested it and 20px higher is about right! Thank you!

**Comment by rlskoeser** [comment]
@gissoo this is the one I downloaded today to check https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=549%3A3284 

I think I used a different version when I initially created the shape (these designs didn't exist at the time).

The coordinates I think I need from you / need to adjust:
- distance from top left of the containing square to the top left of the shape in absolute value (pixels)
- distance from top right of the containing square to the top right of the shape in absolute value (pixels)
- distance from the right to the point of the arrow — I'm not sure if this should be absolute value or percentage, I'm not actually certain how you intended it to scale when the note resizes on mobile. I think I assumed it should be an absolute value based on how the footer design scaled for different screens.

**Comment by gissoo** [comment]
@rlskoeser Noticing now also, I don't know how I missed it when testing this issue, but on desktop the font size of the contextual note is supposed to be 20px and on tablet and mobile it's 16px. Although looking at this now, am wondering 20px is probably too large :\

**Comment by rlskoeser** [comment]
@gissoo I wondered about that too when I was looking at the designs again just now! I saw the font sizes were different, and couldn't remember if I had styled them to be different. (Was also wondering about line heights..) Do you want me to try 20px or do you want to suggest a different size?

**Comment by gissoo** [comment]
No I think it's fine that they are 16px everywhere, don't you think? I think the line height should be 24. It was 22 in my design, I had to revise it, suddenly looked very tight.

**Comment by rlskoeser** [comment]
@gissoo have updated with the adjusted max heights, position, font changes we discussed. (Also, figured out what was setting the top of the text too low; I had padding defined but it was too big. I think I must have measured to the top of the white rectangle, not to the top of the arrow. 🤦‍♀️ )

**Comment by rlskoeser** [comment]
@gissoo corrected shape is now on the site for review! Thanks for all the help figuring it out.

**Comment by gissoo** [comment]
> @gissoo this is the one I downloaded today to check https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=549%3A3284
> 
> I think I used a different version when I initially created the shape (these designs didn't exist at the time).
> 
> The coordinates I think I need from you / need to adjust:
> 
>     * distance from top left of the containing square to the top left of the shape in absolute value (pixels)
> 
>     * distance from top right of the containing square to the top right of the shape in absolute value (pixels)
> 
>     * distance from the right to the point of the arrow — 
>

- @rlskoeser as we discussed [here is a link to the dimensions you need](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1007%3A1170)


>I'm not sure if this should be absolute value or percentage, I'm not actually certain how you intended it to scale when the note resizes on mobile. I think I assumed it should be an absolute value based on how the footer design scaled for different screens.
>

- As we discussed, we want it to be based on the percentage / not like the footer design. (Want to keep the angle the same now matter how wide the screen is)

**Comment by gissoo** [comment]
@rlskoeser This is fixed now!!!! Thank you so much!!!! No more tall note containers!! I just tested multiple times on iOS Safari, FF, and Chrome
