### ISSUE TITLE
On FF iOS the tip of the contextual note is still appearing on the article page by default

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#93]
I've uninstalled and reinstalled FF on my phone, have no idea why this is happening :( 
![Image from iOS (6).png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/4be598bb-91b8-4c2b-82b7-36bd981ecf3a)

**Comment by rlskoeser** [comment]
Now that I'm looking more carefully, I _think_ that this is an artifact of the max height for the contextual notes being too tall for your phone screen. But I've made an adjustment to move the hidden notes further off-screen just in case. Please test again.

**Comment by gissoo** [comment]
@rlskoeser This is gone now!!! Thank you!!!
