### ISSUE TITLE
On narrow desktop view some contextual note containers are cut off

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/startwords#94]
@rlskoeser I have noticed this below. From the left, on Safari and Chrome only note no.4 appears to be cut off, and on Firefox on the right notes no. 1 and 5 appear to be cut off. 
![Screen Shot 2020-06-22 at 4.41.50 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/136c4f7c-e357-4f05-86c7-49838f760022)

**Comment by rlskoeser** [comment]
@gissoo I thought the margins would always leave enough room for the contextual notes when they were not full width. Do you have a suggestion about how to address this? The only thing I can think of would be adjusting the margins, which I think @thatbudakguy would need to handle (seems like it could have other implications!).

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy This is a bit tricky ... What is even more confusing is that this is not happening to all of the notes. One thing I just noticed now (after burning a wire in my brain :exploding_head: :D) the design intended for the contextual notes to always remain within the margins and as part of the solution for this the idea of flipping the contextual note shape was proposed, which is happening and is correct, but it works only when the browser window is full-width/at its widest on desktop. It starts getting messed up once the window is shrunk. Can we do anything about this?

I know the fact that the design intended for the contextual note shape to always be directly under the reference number might be limiting us/contributing to the problem here. Am I correct? Can that still be the default but then when the window is shrunk the contextual note's positioned could slightly change to always keep it within the margin? (I assume it can still be positioned under the red line...)

**Comment by rlskoeser** [comment]
Ah, ok — yes, I can adjust the positioning logic to slide the contextual note horizontally when it is so far to the edge that it is getting clipped off. I see that on the left side it's possible to get a negative value, I can set a minimum of zero. And I'm sure I can figure out equivalent logic for the right side (something like max left value is browser display width minus note width). 

Pretty sure this will result in some scenarios where the arrow will not be pointing to the reference or even under the red line (when this happens on the left side of the page). I assume that's preferable?

**Comment by gissoo** [comment]
@rlskoeser yes, this makes sense to me!! Thank you for writing.

**Comment by rlskoeser** [comment]
@gissoo have revised horizontal placement to keep notes fully on screen even when margins are small, please review.

**Comment by gissoo** [comment]
@rlskoeser thank you!! Right now on the narrowest views on desktop: on Chrome and Safari it's only happening to note no. 4, and on FF it's happening to notes no. 1 and 5. ![Screen Shot 2020-06-24 at 5.34.59 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/3587a0cf-026a-455e-8c2f-cb3da6ca0c34)

**Comment by rlskoeser** [comment]
@gissoo I was testing by manually resizing the browser so that the margins are small and then adjust until I get a footnote reference that is near one margin or the other (which makes it possible to test with several of them, on both sides). If the arrow of the note is not pointing _directly_ up to the reference (as seems to be the case in your first two screenshots), then this is working as I implemented it.

You have to click on the reference _after_ you have resized the window, because contextual note positioning only happens on click, not when you resize the page. Does this match how you are testing?

I adjusted the horizontal position the bare minimum to have it fully visible, meaning the right or left side will be running along the edge of the browser window. I thought it would be preferable to have it as close to the note as possible. Would you prefer something different?

**Comment by gissoo** [comment]
@rlskoeser wow, thanks for writing. Yes, this is how I was already testing yesterday (clicking on the reference after resizing the window). I just tested again. The problem I showed on left two screens (Safari and Chrome) are solved now! Look here, the right edge of note no.4 is not cut off anymore: ![Screen Shot 2020-06-25 at 2.05.11 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/bcb4ef4b-7552-45bc-928c-b91ddaf13b9a)

However, the problem on FF still exists for notes no. 1 and 5. I don't know why.

How you're describing it about them being visible is what is preferable to me as well. But in FF that's not the case right now. (Note: if this is taking too much effort I'm happy with revising it later in the future)

**Comment by rlskoeser** [comment]
Could we have someone else test to help figure out what's going on? @gwijthoff do you have time to take a quick look?

**Comment by gwijthoff** [comment]
If I'm understanding the issue correctly, yes, it looks like note 1 is cut off on the right side when I resize my desktop Firefox window to the narrowest width possible. @gissoo @rlskoeser 

<img width="452" alt="Screen Shot 2020-06-25 at 2 44 02 PM" src="https://user-images.githubusercontent.com/5580840/85780196-57d2e000-b6f2-11ea-8ec3-2bd6fa49f184.png">

**Comment by rlskoeser** [comment]
@gwijthoff thanks for confirming. I don't understand why I can't duplicate this in FF on my machine!

**Comment by rlskoeser** [comment]
ohhh... or there's a scenario where it's flipped and it shouldn't be — do you get this after clicking it in a different configuration first?

**Comment by rlskoeser** [comment]
FWIW, I was able to get this to happen at least once — weirdly when the reference was closer to the middle of the text than at the edges (which is what I'd been testing). There's a small bug where the `flip` class doesn't get removed (unlikely to matter in real use but impacts testing when you're resizing the window and opening and closing notes); I'm hoping that fixing this bug will help with the placement problem.

**Comment by thatbudakguy** [comment]
@gissoo this is ready for another look!

**Comment by gissoo** [comment]
@thatbudakguy YAY!!! This is AWESOME NOW! OMG thank you!!!!
